export {
  MIN_PASSWORD_LENGTH,
  ACCOUNT_DELETION_PHRASE_EN,
  ACCOUNT_DELETION_PHRASE_AR,
  ACCOUNT_DELETION_PHRASES,
  isAccountDeletionPhraseValid,
  createRegistrationSchema,
  createLoginSchema,
  createProfileSchema,
  toProfileFormData,
  isProfileFormDirty,
  type RegistrationFormData,
  type LoginFormData,
  type ProfileFormData,
  type AuthTranslateFn,
  type ProfileTranslateFn,
  type DeleteAccountInput,
  type DeleteAccountResult,
} from '@asol/auth-core';
