import type { InteractionBaseline } from "./discovery.types";

/** Generated by `npm run simulation:discovery:update`. */
export const INTERACTION_BASELINE: InteractionBaseline = {
  "/": {
    "sourceDigest": "d7f012ab8cb11665867c329865e0a9a2dfff3aff9ff1ff0184c7d78b97f1d6a1",
    "interactionSourceCount": 617,
    "eventIds": [
      "open-page"
    ]
  },
  "/cart": {
    "sourceDigest": "d7f012ab8cb11665867c329865e0a9a2dfff3aff9ff1ff0184c7d78b97f1d6a1",
    "interactionSourceCount": 617,
    "eventIds": [
      "open-page",
      "cart-increase",
      "cart-decrease",
      "cart-remove",
      "cart-checkout"
    ]
  },
  "/categories/[categoryId]": {
    "sourceDigest": "28e216e51ffcebce00d41b1d8f4d0847381bad67a86d970b6527a03724f81a18",
    "interactionSourceCount": 627,
    "eventIds": [
      "open-page",
      "category-item"
    ]
  },
  "/categories/[categoryId]/doctor-appointment/[specialtyId]": {
    "sourceDigest": "28e216e51ffcebce00d41b1d8f4d0847381bad67a86d970b6527a03724f81a18",
    "interactionSourceCount": 627,
    "eventIds": [
      "open-page",
      "doctor-open"
    ]
  },
  "/categories/[categoryId]/sellers/[subcategoryId]": {
    "sourceDigest": "28e216e51ffcebce00d41b1d8f4d0847381bad67a86d970b6527a03724f81a18",
    "interactionSourceCount": 627,
    "eventIds": [
      "open-page",
      "seller-open"
    ]
  },
  "/collections/[collectionId]": {
    "sourceDigest": "28e216e51ffcebce00d41b1d8f4d0847381bad67a86d970b6527a03724f81a18",
    "interactionSourceCount": 627,
    "eventIds": [
      "open-page",
      "collection-item"
    ]
  },
  "/contact-us": {
    "sourceDigest": "838099c74dbbde2aa57381c209518be3768a78071a3ad7573d7bb1f454030992",
    "interactionSourceCount": 18,
    "eventIds": [
      "open-page",
      "contact-submit",
      "contact-channel"
    ]
  },
  "/custom-request": {
    "sourceDigest": "d7f012ab8cb11665867c329865e0a9a2dfff3aff9ff1ff0184c7d78b97f1d6a1",
    "interactionSourceCount": 617,
    "eventIds": [
      "open-page",
      "custom-request-submit",
      "custom-request-image"
    ]
  },
  "/delete-account": {
    "sourceDigest": "25ff4c733931732d97a1c7340c3050efe40536c22ebb7fd747100522bacbc24e",
    "interactionSourceCount": 63,
    "eventIds": [
      "open-page",
      "account-delete-stage"
    ]
  },
  "/favorites": {
    "sourceDigest": "6ad7f3a3a728e45b7129fbdaaa6f24ac086218b5615d651b9bd8031f5c1c02ca",
    "interactionSourceCount": 116,
    "eventIds": [
      "open-page",
      "favorites-products",
      "favorites-sellers",
      "favorites-open"
    ]
  },
  "/forgot-password": {
    "sourceDigest": "5256a6991486c87806db04049a7dec59fa6033344832cc9b9b16a5be9bf4f79a",
    "interactionSourceCount": 77,
    "eventIds": [
      "open-page",
      "password-request"
    ]
  },
  "/home": {
    "sourceDigest": "018c2384e52993c4094e43ef52df8e63693955dbf91fe34d3220c126ccc558b9",
    "interactionSourceCount": 630,
    "eventIds": [
      "open-page",
      "home-search",
      "home-category",
      "home-promotion"
    ]
  },
  "/login": {
    "sourceDigest": "25ff4c733931732d97a1c7340c3050efe40536c22ebb7fd747100522bacbc24e",
    "interactionSourceCount": 63,
    "eventIds": [
      "open-page",
      "login-submit",
      "login-as-guest",
      "login-forgot-password",
      "login-registration"
    ]
  },
  "/notifications": {
    "sourceDigest": "f088772a5a3388509c9e6621f148632286b9eb2c9e59ca9e6a1136f807f5cca1",
    "interactionSourceCount": 22,
    "eventIds": [
      "open-page",
      "notification-filter",
      "notification-read",
      "notification-open",
      "notification-dismiss"
    ]
  },
  "/notifications/chat": {
    "sourceDigest": "c80aeee866cec9f113732e62d3f340dce767d50be6c50800a7b45664bd0f86ef",
    "interactionSourceCount": 90,
    "eventIds": [
      "open-page",
      "chat-reply"
    ]
  },
  "/orders": {
    "sourceDigest": "bf0ff9d9623d7a5e05a92daafe263a838d7f2c361e94acdfeb034aa33fa61dee",
    "interactionSourceCount": 673,
    "eventIds": [
      "open-page",
      "orders-open"
    ]
  },
  "/orders/[orderId]": {
    "sourceDigest": "bf0ff9d9623d7a5e05a92daafe263a838d7f2c361e94acdfeb034aa33fa61dee",
    "interactionSourceCount": 673,
    "eventIds": [
      "open-page",
      "order-action"
    ]
  },
  "/orders/details": {
    "sourceDigest": "bf0ff9d9623d7a5e05a92daafe263a838d7f2c361e94acdfeb034aa33fa61dee",
    "interactionSourceCount": 673,
    "eventIds": [
      "open-page",
      "order-action"
    ]
  },
  "/privacy-policy": {
    "sourceDigest": "bc1857e9190aa35ce7c1bff9846e415572bcb80f39c293024add6cc73da9cfcf",
    "interactionSourceCount": 1,
    "eventIds": [
      "open-page",
      "privacy-email"
    ]
  },
  "/product": {
    "sourceDigest": "d7f012ab8cb11665867c329865e0a9a2dfff3aff9ff1ff0184c7d78b97f1d6a1",
    "interactionSourceCount": 617,
    "eventIds": [
      "open-page",
      "product-add-cart",
      "product-favorite",
      "product-share",
      "product-review",
      "product-contact",
      "product-owner-profile"
    ]
  },
  "/profile": {
    "sourceDigest": "d7f012ab8cb11665867c329865e0a9a2dfff3aff9ff1ff0184c7d78b97f1d6a1",
    "interactionSourceCount": 617,
    "eventIds": [
      "open-page",
      "profile-follow",
      "profile-share",
      "profile-custom-request",
      "profile-contact",
      "profile-save"
    ]
  },
  "/profile/pharmacy-catalog": {
    "sourceDigest": "d7f012ab8cb11665867c329865e0a9a2dfff3aff9ff1ff0184c7d78b97f1d6a1",
    "interactionSourceCount": 617,
    "eventIds": [
      "open-page",
      "pharmacy-category",
      "pharmacy-toggle",
      "pharmacy-save"
    ]
  },
  "/registration": {
    "sourceDigest": "25ff4c733931732d97a1c7340c3050efe40536c22ebb7fd747100522bacbc24e",
    "interactionSourceCount": 63,
    "eventIds": [
      "open-page",
      "registration-submit",
      "registration-login"
    ]
  },
  "/s/product": {
    "sourceDigest": "d7f012ab8cb11665867c329865e0a9a2dfff3aff9ff1ff0184c7d78b97f1d6a1",
    "interactionSourceCount": 617,
    "eventIds": [
      "open-page"
    ]
  },
  "/s/profile": {
    "sourceDigest": "d7f012ab8cb11665867c329865e0a9a2dfff3aff9ff1ff0184c7d78b97f1d6a1",
    "interactionSourceCount": 617,
    "eventIds": [
      "open-page"
    ]
  },
  "/search": {
    "sourceDigest": "1a0f83871bc2856626d20e60a2df98ff4c9612fb9c525a364f5a704cec03c726",
    "interactionSourceCount": 108,
    "eventIds": [
      "open-page",
      "search-submit",
      "search-product",
      "search-seller"
    ]
  },
  "/settings": {
    "sourceDigest": "72dd466ae875a047bde3b0282e41906d632cbc7543a5872a9e173707af3b02a8",
    "interactionSourceCount": 635,
    "eventIds": [
      "open-page",
      "settings-check-update",
      "settings-clear-data",
      "settings-notifications"
    ]
  },
  "/settings/notifications": {
    "sourceDigest": "72dd466ae875a047bde3b0282e41906d632cbc7543a5872a9e173707af3b02a8",
    "interactionSourceCount": 635,
    "eventIds": [
      "open-page",
      "notifications-permission",
      "notifications-test",
      "notifications-revoke-device"
    ]
  },
  "/specialty-request": {
    "sourceDigest": "c80aeee866cec9f113732e62d3f340dce767d50be6c50800a7b45664bd0f86ef",
    "interactionSourceCount": 90,
    "eventIds": [
      "open-page",
      "specialty-main",
      "specialty-sub",
      "specialty-submit"
    ]
  }
} as const;
