import type { InteractionBaseline } from "./discovery.types";

/** Generated by `npm run simulation:discovery:update`. */
export const INTERACTION_BASELINE: InteractionBaseline = {
  "/": {
    "sourceDigest": "b8940b708f6ff5f9ea52f7630daf2c188327c4c494a2cd722fe1663be30f0661",
    "interactionSourceCount": 626,
    "eventIds": [
      "open-page"
    ]
  },
  "/cart": {
    "sourceDigest": "b8940b708f6ff5f9ea52f7630daf2c188327c4c494a2cd722fe1663be30f0661",
    "interactionSourceCount": 626,
    "eventIds": [
      "open-page",
      "cart-increase",
      "cart-decrease",
      "cart-remove",
      "cart-checkout"
    ]
  },
  "/categories/[categoryId]": {
    "sourceDigest": "3a477b56ae90177d3996019c379ee535f42088ec31f87b127c40709ce30e504a",
    "interactionSourceCount": 636,
    "eventIds": [
      "open-page",
      "category-item"
    ]
  },
  "/categories/[categoryId]/doctor-appointment/[specialtyId]": {
    "sourceDigest": "3a477b56ae90177d3996019c379ee535f42088ec31f87b127c40709ce30e504a",
    "interactionSourceCount": 636,
    "eventIds": [
      "open-page",
      "doctor-open"
    ]
  },
  "/categories/[categoryId]/sellers/[subcategoryId]": {
    "sourceDigest": "3a477b56ae90177d3996019c379ee535f42088ec31f87b127c40709ce30e504a",
    "interactionSourceCount": 636,
    "eventIds": [
      "open-page",
      "seller-open"
    ]
  },
  "/collections/[collectionId]": {
    "sourceDigest": "3a477b56ae90177d3996019c379ee535f42088ec31f87b127c40709ce30e504a",
    "interactionSourceCount": 636,
    "eventIds": [
      "open-page",
      "collection-item"
    ]
  },
  "/contact-us": {
    "sourceDigest": "1afe321aed7ac7fcb51bb114c2caa1d3e802215c102a78095af4db6c9ab984c3",
    "interactionSourceCount": 29,
    "eventIds": [
      "open-page",
      "contact-submit",
      "contact-channel"
    ]
  },
  "/custom-request": {
    "sourceDigest": "b8940b708f6ff5f9ea52f7630daf2c188327c4c494a2cd722fe1663be30f0661",
    "interactionSourceCount": 626,
    "eventIds": [
      "open-page",
      "custom-request-submit",
      "custom-request-image"
    ]
  },
  "/delete-account": {
    "sourceDigest": "78bbb8e2e8c51382d10d5ea7f617c4dfde8b595581147bc5701f0a553c4e056a",
    "interactionSourceCount": 74,
    "eventIds": [
      "open-page",
      "account-delete-stage"
    ]
  },
  "/favorites": {
    "sourceDigest": "76fe8fb3ca736f6990492f03b99e25a96a10daf1a7cb534556da00c5e4d3d255",
    "interactionSourceCount": 127,
    "eventIds": [
      "open-page",
      "favorites-products",
      "favorites-sellers",
      "favorites-open"
    ]
  },
  "/forgot-password": {
    "sourceDigest": "5b99414830db6c115dfd3633928b4893916ae9730c3166536fe1cce23931892d",
    "interactionSourceCount": 88,
    "eventIds": [
      "open-page",
      "password-request"
    ]
  },
  "/home": {
    "sourceDigest": "0fa3034bb41e8ca19db885c881ca745d6dcfb9dcb2e29404ac2b6d1086b9e928",
    "interactionSourceCount": 639,
    "eventIds": [
      "open-page",
      "home-search",
      "home-category",
      "home-promotion"
    ]
  },
  "/login": {
    "sourceDigest": "78bbb8e2e8c51382d10d5ea7f617c4dfde8b595581147bc5701f0a553c4e056a",
    "interactionSourceCount": 74,
    "eventIds": [
      "open-page",
      "login-submit",
      "login-as-guest",
      "login-forgot-password",
      "login-registration"
    ]
  },
  "/notifications": {
    "sourceDigest": "72aeee56c9c69267bbdc6b78064bd633908df48c6c3dfe14d8f930ac9327d808",
    "interactionSourceCount": 22,
    "eventIds": [
      "open-page",
      "notification-filter",
      "notification-read",
      "notification-open",
      "notification-dismiss"
    ]
  },
  "/notifications/chat": {
    "sourceDigest": "57a39da81cc5dd6565607f829ab6bec48d0ef0c32af892daec479b8370154334",
    "interactionSourceCount": 101,
    "eventIds": [
      "open-page",
      "chat-reply"
    ]
  },
  "/orders": {
    "sourceDigest": "9692b29b9dd0731bc1a9d3a179360d0cb22c5414fb2ba2bb5f813260a868edae",
    "interactionSourceCount": 682,
    "eventIds": [
      "open-page",
      "orders-open"
    ]
  },
  "/orders/[orderId]": {
    "sourceDigest": "9692b29b9dd0731bc1a9d3a179360d0cb22c5414fb2ba2bb5f813260a868edae",
    "interactionSourceCount": 682,
    "eventIds": [
      "open-page",
      "order-action"
    ]
  },
  "/orders/details": {
    "sourceDigest": "9692b29b9dd0731bc1a9d3a179360d0cb22c5414fb2ba2bb5f813260a868edae",
    "interactionSourceCount": 682,
    "eventIds": [
      "open-page",
      "order-action"
    ]
  },
  "/privacy-policy": {
    "sourceDigest": "bc1857e9190aa35ce7c1bff9846e415572bcb80f39c293024add6cc73da9cfcf",
    "interactionSourceCount": 1,
    "eventIds": [
      "open-page",
      "privacy-email"
    ]
  },
  "/product": {
    "sourceDigest": "b8940b708f6ff5f9ea52f7630daf2c188327c4c494a2cd722fe1663be30f0661",
    "interactionSourceCount": 626,
    "eventIds": [
      "open-page",
      "product-add-cart",
      "product-favorite",
      "product-share",
      "product-review",
      "product-contact",
      "product-owner-profile"
    ]
  },
  "/profile": {
    "sourceDigest": "b8940b708f6ff5f9ea52f7630daf2c188327c4c494a2cd722fe1663be30f0661",
    "interactionSourceCount": 626,
    "eventIds": [
      "open-page",
      "profile-follow",
      "profile-share",
      "profile-custom-request",
      "profile-contact",
      "profile-save"
    ]
  },
  "/profile/pharmacy-catalog": {
    "sourceDigest": "b8940b708f6ff5f9ea52f7630daf2c188327c4c494a2cd722fe1663be30f0661",
    "interactionSourceCount": 626,
    "eventIds": [
      "open-page",
      "pharmacy-category",
      "pharmacy-toggle",
      "pharmacy-save"
    ]
  },
  "/registration": {
    "sourceDigest": "78bbb8e2e8c51382d10d5ea7f617c4dfde8b595581147bc5701f0a553c4e056a",
    "interactionSourceCount": 74,
    "eventIds": [
      "open-page",
      "registration-submit",
      "registration-login"
    ]
  },
  "/s/product": {
    "sourceDigest": "b8940b708f6ff5f9ea52f7630daf2c188327c4c494a2cd722fe1663be30f0661",
    "interactionSourceCount": 626,
    "eventIds": [
      "open-page"
    ]
  },
  "/s/profile": {
    "sourceDigest": "b8940b708f6ff5f9ea52f7630daf2c188327c4c494a2cd722fe1663be30f0661",
    "interactionSourceCount": 626,
    "eventIds": [
      "open-page"
    ]
  },
  "/search": {
    "sourceDigest": "271dcc248d26b2f14a64d1804fc7c03d6742654533870d2d1e1e5d6ac052ef29",
    "interactionSourceCount": 118,
    "eventIds": [
      "open-page",
      "search-submit",
      "search-product",
      "search-seller"
    ]
  },
  "/settings": {
    "sourceDigest": "70579da78d84b3e4ca1d2828bf63478bcb075eb2e485189e51151570a0321904",
    "interactionSourceCount": 644,
    "eventIds": [
      "open-page",
      "settings-check-update",
      "settings-clear-data",
      "settings-notifications"
    ]
  },
  "/settings/notifications": {
    "sourceDigest": "70579da78d84b3e4ca1d2828bf63478bcb075eb2e485189e51151570a0321904",
    "interactionSourceCount": 644,
    "eventIds": [
      "open-page",
      "notifications-permission",
      "notifications-test",
      "notifications-revoke-device"
    ]
  },
  "/specialty-request": {
    "sourceDigest": "57a39da81cc5dd6565607f829ab6bec48d0ef0c32af892daec479b8370154334",
    "interactionSourceCount": 101,
    "eventIds": [
      "open-page",
      "specialty-main",
      "specialty-sub",
      "specialty-submit"
    ]
  }
} as const;
