import { execFileSync } from 'node:child_process';

import {
  KNOWN_UNSHIPPED,
  shippedRoutes,
  type OwnedRoute,
} from '../route-ownership-coverage';

/**
 * Which account answers which request, as a generated fact.
 *
 * After the cutover a client's destination is no longer "the app" — it is one of
 * eight origins chosen per route and method. Every question that used to be
 * answered by reading `src/app/api` now needs three facts at once: who owns the
 * route, which origin that is, and whether the owner actually ships a handler.
 * Holding those apart is what let ownership be declared for 63 pairs that
 * answered `404`, sign-in among them.
 *
 * Generated from the AST ownership inventory and the services' own route files,
 * so it cannot drift from what is deployed. Never hand-edit it.
 */

const ACCOUNT_ORIGINS: Readonly<Record<string, { project: string; envVar: string }>> = {
  gova: { project: 'gova', envVar: 'NEXT_PUBLIC_ASOL_API_BASE_URL' },
  control: { project: 'asol-control', envVar: 'NEXT_PUBLIC_ASOL_CONTROL_URL' },
  notifications: { project: 'asol-notifications', envVar: 'NEXT_PUBLIC_ASOL_NOTIFICATIONS_URL' },
  products: { project: 'asol-products', envVar: 'NEXT_PUBLIC_ASOL_PRODUCTS_URL' },
  orders: { project: 'asol-orders', envVar: 'NEXT_PUBLIC_ASOL_ORDERS_URL' },
  profiles: { project: 'asol-profiles', envVar: 'NEXT_PUBLIC_ASOL_PROFILES_URL' },
  submain: { project: 'asol-submain', envVar: 'NEXT_PUBLIC_ASOL_SUBMAIN_URL' },
  sub2main: { project: 'asol-sub2main', envVar: 'NEXT_PUBLIC_ASOL_SUB2MAIN_URL' },
};

const SERVICE_DIRS: Readonly<Record<string, string>> = {
  control: 'services/control',
  notifications: 'services/notifications',
  products: 'services/products',
  orders: 'services/orders',
  profiles: 'services/profiles',
  submain: 'services/submain',
  sub2main: 'services/sub2main',
};

function readOwnedRoutes(): OwnedRoute[] {
  const output = execFileSync('npx', ['tsx', 'scripts/api-route-inventory.ts'], {
    cwd: process.cwd(),
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
  });
  return output
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      const [method, route, owner] = line.split('\t');
      return { method: method!, route: route!, owner: owner! };
    });
}

export function renderAccountRoutingCatalog(): string {
  const owned = readOwnedRoutes();
  const shipped = new Map<string, Map<string, Set<string>>>();
  for (const [owner, dir] of Object.entries(SERVICE_DIRS)) shipped.set(owner, shippedRoutes(dir));
  const known = new Set(KNOWN_UNSHIPPED);

  const byOwner = new Map<string, OwnedRoute[]>();
  for (const entry of owned) {
    if (!byOwner.has(entry.owner)) byOwner.set(entry.owner, []);
    byOwner.get(entry.owner)!.push(entry);
  }

  const lines: string[] = [
    '<!-- Generated by npm run docs:generate. Do not edit by hand. -->',
    '',
    '# Account Routing Catalog',
    '',
    'Every Business API route and method, the account that owns it, and whether',
    'that account ships a handler for it today.',
    '',
    'A client resolves the origin from the owner column through the route',
    'registry in `@asol/account-bridge/routes`; the same registry drives the gova',
    'compatibility boundary, which answers a legacy request with a `307` to that',
    'origin. `OPTIONS` is transport on each receiving origin, not ownership, so it',
    'is listed as `gova/dev` and answered wherever the request lands.',
    '',
    '**`unshipped` means a live `404`.** Those pairs are tracked in',
    '`scripts/route-ownership-coverage.ts` and enforced by',
    '`npm run test:route-ownership`; see',
    '[owned-route-not-shipped.md](../../../08-troubleshooting/problems/owned-route-not-shipped.md).',
    '',
    '## Accounts',
    '',
    '| Account | Vercel project | Origin variable | Owned pairs | Shipped | Unshipped |',
    '| --- | --- | --- | ---: | ---: | ---: |',
  ];

  const owners = [...byOwner.keys()].sort();
  for (const owner of owners) {
    const entries = byOwner.get(owner)!;
    const business = entries.filter((entry) => entry.method !== 'OPTIONS');
    const meta = ACCOUNT_ORIGINS[owner];
    const missing = business.filter(
      (entry) => !shipped.get(owner)?.get(entry.route)?.has(entry.method),
    ).length;
    const shippedCount = business.length - (SERVICE_DIRS[owner] ? missing : 0);
    lines.push(
      `| \`${owner}\` | ${meta ? `\`${meta.project}\`` : '—'} | ${meta ? `\`${meta.envVar}\`` : '—'} ` +
        `| ${business.length} | ${SERVICE_DIRS[owner] ? shippedCount : business.length} ` +
        `| ${SERVICE_DIRS[owner] ? missing : 0} |`,
    );
  }

  for (const owner of owners) {
    const entries = byOwner
      .get(owner)!
      .filter((entry) => entry.method !== 'OPTIONS')
      .sort((a, b) => a.route.localeCompare(b.route) || a.method.localeCompare(b.method));
    if (entries.length === 0) continue;

    lines.push('', `## \`${owner}\``, '');
    if (owner === 'gova/dev') {
      lines.push(
        'Served by gova itself: its own health surface and the development-only',
        'routes, which are omitted from the production artifact entirely.',
        '',
      );
    }
    lines.push('| Method | Route | Status |', '| --- | --- | --- |');
    for (const entry of entries) {
      const dir = SERVICE_DIRS[owner];
      const status = !dir
        ? 'gova'
        : shipped.get(owner)?.get(entry.route)?.has(entry.method)
          ? 'shipped'
          : known.has(`${entry.method} ${entry.route}`)
            ? '**unshipped (tracked)**'
            : '**unshipped**';
      lines.push(`| \`${entry.method}\` | \`${entry.route}\` | ${status} |`);
    }
  }

  return `${lines.join('\n')}\n`;
}
