import type { UiPageDefinition } from "../domain/ui-page-definition";

/**
 * One registry for every App Router page. Its route templates are intentionally
 * value-free so production diagnostics cannot disclose dynamic route values.
 */
export const UI_PAGE_REGISTRY = [
  { route: "/", id: "splash", uid: "splash-QQH00C" },
  { route: "/cart", id: "cart", uid: "cart-4Uxneo" },
  { route: "/categories/[categoryId]", id: "categories.category", uid: "categories.category-mGnD4s" },
  { route: "/categories/[categoryId]/doctor-appointment/[specialtyId]", id: "categories.doctor-appointment", uid: "categories.doctor-appointment-Hz94CJ" },
  { route: "/categories/[categoryId]/sellers/[subcategoryId]", id: "categories.sellers", uid: "categories.sellers-sMcm71" },
  { route: "/collections/[collectionId]", id: "collections.collection", uid: "collections.collection-hp2yEy" },
  { route: "/contact-us", id: "contact", uid: "contact-Gz36zP" },
  { route: "/custom-request", id: "custom-request", uid: "custom-request-5tDtgF" },
  { route: "/delete-account", id: "delete-account", uid: "delete-account-VTvZ9s" },
  { route: "/dev/catalog-studio", id: "dev.catalog-studio", uid: "dev.catalog-studio-NtXZ7T" },
  { route: "/dev/category-selector", id: "dev.category-selector", uid: "dev.category-selector-9DHf4S" },
  { route: "/dev/cloud-accounts", id: "dev.cloud-accounts", uid: "dev.cloud-accounts-TFM679" },
  { route: "/dev/data-health", id: "dev.data-health", uid: "dev.data-health-9I4WAC" },
  { route: "/dev/deploy-all", id: "dev.deploy-all", uid: "dev.deploy-all-JLw8HH" },
  { route: "/dev/dev-cloud-backup", id: "dev.cloud-backup", uid: "dev.cloud-backup-JP90Z5" },
  { route: "/dev/google-play-console", id: "dev.google-play-console", uid: "dev.google-play-console-PB0oa1" },
  { route: "/dev/monitor", id: "dev.monitor", uid: "dev.monitor-lDC1y5" },
  { route: "/dev/notification-tests", id: "dev.notification-tests", uid: "dev.notification-tests-2PhY55" },
  { route: "/dev/ota-releases", id: "dev.ota-releases", uid: "dev.ota-releases-m1rQhj" },
  { route: "/dev/release-console", id: "dev.release-console", uid: "dev.release-console-9FJhLU" },
  { route: "/favorites", id: "favorites", uid: "favorites-Mz4NXb" },
  { route: "/forgot-password", id: "forgot-password", uid: "forgot-password-1mn6KC" },
  { route: "/home", id: "home", uid: "home-LY13AG" },
  { route: "/login", id: "login", uid: "login-yX6jJT" },
  { route: "/notifications", id: "notifications", uid: "notifications-6sKi8b" },
  { route: "/notifications/chat", id: "notifications.chat", uid: "notifications.chat-LuMy5j" },
  { route: "/orders", id: "orders", uid: "orders-T7pmOw" },
  { route: "/orders/[orderId]", id: "orders.details", uid: "orders.details-N2dcj3" },
  { route: "/orders/details", id: "orders.details-static", uid: "orders.details-static-53SAaH" },
  { route: "/privacy-policy", id: "privacy-policy", uid: "privacy-policy-W4Cy9O" },
  { route: "/product", id: "product", uid: "product-1iwyOc" },
  { route: "/profile", id: "profile", uid: "profile-b75MA7" },
  { route: "/profile/pharmacy-catalog", id: "profile.pharmacy-catalog", uid: "profile.pharmacy-catalog-4FH3N1" },
  { route: "/registration", id: "registration", uid: "registration-X6sEIb" },
  { route: "/s/product", id: "share.product", uid: "share.product-eDPE33" },
  { route: "/s/profile", id: "share.profile", uid: "share.profile-R1BjDK" },
  { route: "/search", id: "search", uid: "search-8G0nWq" },
  { route: "/settings", id: "settings", uid: "settings-c250Zl" },
  { route: "/settings/notifications", id: "settings.notifications", uid: "settings.notifications-u4tT8E" },
  { route: "/specialty-request", id: "specialty-request", uid: "specialty-request-7mLMNS" },
  { route: "/super-admin/catalog", id: "super-admin.catalog", uid: "super-admin.catalog-i7MxX9" },
  { route: "/super-admin/data-health", id: "super-admin.data-health", uid: "super-admin.data-health-HSk1iD" },
  { route: "/super-admin/dev-cloud-backup", id: "super-admin.cloud-backup", uid: "super-admin.cloud-backup-47gqWF" },
  { route: "/super-admin/featured-marquee", id: "super-admin.featured-marquee", uid: "super-admin.featured-marquee-XtBeJ1" },
  { route: "/super-admin/google-play-console", id: "super-admin.google-play-console", uid: "super-admin.google-play-console-XJOa5Y" },
  { route: "/super-admin/google-play-store-assets", id: "super-admin.google-play-store-assets", uid: "super-admin.google-play-store-assets-BRWyi8" },
  { route: "/super-admin/hero-slider", id: "super-admin.hero-slider", uid: "super-admin.hero-slider-IbR4zy" },
  { route: "/super-admin/logs", id: "super-admin.logs", uid: "super-admin.logs-LWtC3E" },
  { route: "/super-admin/notifications-broadcast", id: "super-admin.notifications-broadcast", uid: "super-admin.notifications-broadcast-ho0JZr" },
  { route: "/super-admin/ota-releases", id: "super-admin.ota-releases", uid: "super-admin.ota-releases-9l86YI" },
  { route: "/super-admin/production-deploy", id: "super-admin.production-deploy", uid: "super-admin.production-deploy-elBaY4" },
  { route: "/super-admin/simulation", id: "super-admin.simulation", uid: "super-admin.simulation-CVZJ9X" },
  { route: "/super-admin/simulation/[pageId]", id: "super-admin.simulation.page", uid: "super-admin.simulation.page-1KOOKs" },
  { route: "/super-admin/trending-ribbon", id: "super-admin.trending-ribbon", uid: "super-admin.trending-ribbon-iX5fh8" },
  { route: "/super-admin/users", id: "super-admin.users", uid: "super-admin.users-A6tbIe" },
] as const satisfies readonly UiPageDefinition[];
