import type { MarketplaceDb } from "../db/client";
import type { MarketplaceOrderTable } from "../db/schema";
const SAFE=/^[a-z_]+$/;
export class BaseRepository<T extends Record<string,unknown>> { constructor(protected db:MarketplaceDb, protected table:MarketplaceOrderTable){} async findById(id:string):Promise<T|null>{return (await this.db.execute(`SELECT * FROM ${this.table} WHERE id=? LIMIT 1`,[id]))[0] as T??null} async find(where:Record<string,unknown>={}):Promise<T[]>{const entries=Object.entries(where); if(entries.some(([k])=>!SAFE.test(k)))throw new Error("Invalid query field"); const clause=entries.length?` WHERE ${entries.map(([k])=>`${k}=?`).join(" AND ")}`:""; return await this.db.execute(`SELECT * FROM ${this.table}${clause}`,entries.map(([,v])=>v)) as T[]} async create(row:T):Promise<T>{const keys=Object.keys(row); if(keys.some(k=>!SAFE.test(k)))throw new Error("Invalid field"); await this.db.execute(`INSERT INTO ${this.table} (${keys.join(",")}) VALUES (${keys.map(()=>"?").join(",")})`,keys.map(k=>row[k])); return row} async update(id:string,patch:Partial<T>):Promise<T>{if("calculated_status" in patch&&this.table==="orders")throw new Error("Order calculated status cannot be manually edited"); const keys=Object.keys(patch); if(!keys.length)return (await this.findById(id))!; await this.db.execute(`UPDATE ${this.table} SET ${keys.map(k=>`${k}=?`).join(",")} WHERE id=?`,[...keys.map(k=>patch[k]),id]); const result=await this.findById(id); if(!result)throw new Error(`${this.table} not found`); return result} async delete(id:string){await this.db.execute(`DELETE FROM ${this.table} WHERE id=?`,[id])} }
export class OrderRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"orders")}}
export class SellerOrderRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"seller_orders")}}
export class OrderItemRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"order_items")}}
export class CustomRequestItemRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"custom_request_items")}}
export class CustomRequestImageRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"custom_request_images")}}
export class ShipmentRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"shipments")}}
export class ShipmentItemRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"shipment_items")}}
export class PaymentRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"payments")}}
export class RefundRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"refunds")}}
export class CancellationRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"cancellations")}}
export class ReturnRequestRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"return_requests")}}
export class ReplacementRequestRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"replacement_requests")}}
export class DisputeRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"disputes")}}
export class AuditTrailRepository<T extends Record<string,unknown>=Record<string,unknown>> extends BaseRepository<T>{constructor(db:MarketplaceDb){super(db,"audit_trail")}}

