export function cartPageCopy(locale: "ar" | "en") {
  return locale === "ar" ? {
    title: "السلة",
    description: "راجع المنتجات والخدمات قبل إرسالها كطلب رسمي بنظام الدفع عند الاستلام.",
    clear: "تفريغ السلة",
    emptyTitle: "السلة فارغة",
    emptyText: "عند إضافة منتج أو خدمة ستظهر هنا، وستظهر النقطة الحمراء في الهيدر.",
    browse: "تصفح المنتجات",
    seller: "البائع",
    viewSeller: "عرض بروفايل البائع",
    noImage: "بدون صورة",
    unitPrice: "سعر الوحدة",
    summary: "ملخص السلة",
    coupon: "كود الخصم",
    couponHint: "يمكن إدخال أكثر من كود بفاصلة.",
    itemCount: "عدد العناصر",
    productsTotal: "إجمالي المنتجات",
    loadingDiscounts: "جاري حساب الخصومات",
    total: "الإجمالي",
    submit: "إرسال الطلب",
    submitHint: "سيتم إنشاء الطلب الرسمي من قاعدة البيانات، والدفع عند الاستلام فقط.",
  } : {
    title: "Cart",
    description: "Review products and services before submitting an official cash-on-delivery order.",
    clear: "Clear cart",
    emptyTitle: "Your cart is empty",
    emptyText: "Products and services you add will appear here.",
    browse: "Browse products",
    seller: "Seller",
    viewSeller: "View seller profile",
    noImage: "No image",
    unitPrice: "Unit price",
    summary: "Cart summary",
    coupon: "Discount code",
    couponHint: "Separate multiple codes with commas.",
    itemCount: "Items",
    productsTotal: "Products total",
    loadingDiscounts: "Calculating discounts",
    total: "Total",
    submit: "Submit order",
    submitHint: "The official order will be created in the database. Payment is cash on delivery only.",
  };
}
