import { notificationsDataSource } from "../../../core";
import "server-only";
import type { IDatabaseClient } from "../../../core/database/database-client.interface";
import type { DeleteNotificationTokenInput, NotificationChatPreferenceChanges, NotificationChatPreferences, NotificationDeliveryPreference, RegisteredNotificationToken, RegisterNotificationTokenInput } from "@asol/notifications-core";
type TokenRow={id:string;uid:string;platform:RegisterNotificationTokenInput['platform'];provider:string;deviceId:string;token:string;locale:string;enabled:boolean|number;lastSeenAt:string|null;createdAt:string|null;updatedAt:string|null;deletedAt:string|null};
const TOKEN_SELECT=`SELECT id, uid, platform, provider, device_id AS deviceId, token, locale, enabled, last_seen_at AS lastSeenAt, created_at AS createdAt, updated_at AS updatedAt, deleted_at AS deletedAt FROM user_notification_tokens`;
function makeTokenId(uid:string,platform:RegisterNotificationTokenInput['platform']){return `ntok_${uid}_${platform}`.replace(/[^a-zA-Z0-9_:-]/g,"_")}
export class UserNotificationTokenRepository{
 constructor(private readonly database:IDatabaseClient=notificationsDataSource){}
 async upsert(input:RegisterNotificationTokenInput):Promise<RegisteredNotificationToken>{const now=new Date().toISOString(),id=makeTokenId(input.uid,input.platform),locale=input.locale==='en'?'en':'ar';await this.releaseTokenValue(input.token,input.uid,input.platform);await this.database.execute(`INSERT INTO user_notification_tokens (id,uid,platform,provider,device_id,token,locale,enabled,last_seen_at,created_at,updated_at,deleted_at) VALUES (?,?,?,?,?,?,?,1,?,?,?,NULL) ON CONFLICT(uid,platform) DO UPDATE SET provider=excluded.provider,device_id=excluded.device_id,token=excluded.token,locale=excluded.locale,enabled=1,last_seen_at=excluded.last_seen_at,updated_at=excluded.updated_at,deleted_at=NULL`,[id,input.uid,input.platform,input.provider,input.deviceId,input.token,locale,now,now,now]);const saved=await this.findByUidPlatform(input.uid,input.platform);if(!saved)throw new Error('notificationTokenSaveFailed');return toDomainToken(saved)}
 private async releaseTokenValue(token:string,uid:string,platform:RegisterNotificationTokenInput['platform']){const rows=await this.database.execute('SELECT id,uid,platform FROM user_notification_tokens WHERE token = ?',[token]) as any[];const ids=rows.filter(r=>r.uid!==uid||r.platform!==platform).map(r=>r.id);if(ids.length)await this.database.execute(`DELETE FROM user_notification_tokens WHERE id IN (${ids.map(()=>'?').join(',')})`,ids)}
 async listByUid(uid:string){const rows=await this.database.execute(`${TOKEN_SELECT} WHERE uid=? AND enabled=1 AND deleted_at IS NULL`,[uid]) as TokenRow[];return rows.map(toDomainToken)}
 async listByUids(uids:string[]){return Object.fromEntries(await Promise.all(uids.map(async uid=>[uid,await this.listByUid(uid)] as const)))}
 async setChatPreferences(uid:string,c:NotificationChatPreferenceChanges):Promise<NotificationChatPreferences>{const now=new Date().toISOString(),s=typeof c.specialtyRequestsEnabled==='boolean'?(c.specialtyRequestsEnabled?1:0):null,p=typeof c.productConversationsEnabled==='boolean'?(c.productConversationsEnabled?1:0):null;await this.database.execute(`INSERT INTO user_notification_preferences (uid,specialty_requests_enabled,product_conversations_enabled,updated_at) VALUES (?,COALESCE(?,1),COALESCE(?,1),?) ON CONFLICT(uid) DO UPDATE SET specialty_requests_enabled=COALESCE(?,specialty_requests_enabled),product_conversations_enabled=COALESCE(?,product_conversations_enabled),updated_at=excluded.updated_at`,[uid,s,p,now,s,p]);return this.chatPreferences(uid)}
 async chatPreferences(uid:string):Promise<NotificationChatPreferences>{const r=(await this.database.execute('SELECT specialty_requests_enabled AS specialtyRequestsEnabled, product_conversations_enabled AS productConversationsEnabled FROM user_notification_preferences WHERE uid=? LIMIT 1',[uid]))[0] as any;return r?{specialtyRequestsEnabled:Boolean(r.specialtyRequestsEnabled),productConversationsEnabled:Boolean(r.productConversationsEnabled)}:{specialtyRequestsEnabled:true,productConversationsEnabled:true}}
 private async filterEnabled(uids:string[],column:string){const unique=[...new Set(uids.filter(Boolean))];if(!unique.length)return[];const rows=await this.database.execute(`SELECT uid, ${column} AS enabled FROM user_notification_preferences WHERE uid IN (${unique.map(()=>'?').join(',')})`,unique) as any[];const disabled=new Set(rows.filter(r=>!Boolean(r.enabled)).map(r=>r.uid));return unique.filter(uid=>!disabled.has(uid))}
 filterSpecialtyRequestsEnabled(uids:string[]){return this.filterEnabled(uids,'specialty_requests_enabled')}
 async getPushEnabled(uid:string):Promise<NotificationDeliveryPreference>{const r=(await this.database.execute('SELECT push_enabled AS pushEnabled FROM user_notification_preferences WHERE uid=? LIMIT 1',[uid]))[0] as any;return{pushEnabled:r?Boolean(r.pushEnabled):true}}
 async setPushEnabled(uid:string,pushEnabled:boolean):Promise<NotificationDeliveryPreference>{await this.database.execute(`INSERT INTO user_notification_preferences (uid,push_enabled,updated_at) VALUES (?,?,?) ON CONFLICT(uid) DO UPDATE SET push_enabled=excluded.push_enabled,updated_at=excluded.updated_at`,[uid,pushEnabled?1:0,new Date().toISOString()]);return{pushEnabled}}
 filterPushEnabled(uids:string[]){return this.filterEnabled(uids,'push_enabled')}
 async disable(input:DeleteNotificationTokenInput){const now=new Date().toISOString();if(input.tokenId){await this.database.execute('UPDATE user_notification_tokens SET enabled=0,deleted_at=?,updated_at=? WHERE id=? AND uid=?',[now,now,input.tokenId,input.uid]);return}if(!input.deviceId)throw new Error('notificationTokenIdentifierRequired');await this.database.execute('UPDATE user_notification_tokens SET enabled=0,deleted_at=?,updated_at=? WHERE uid=? AND device_id=? AND deleted_at IS NULL',[now,now,input.uid,input.deviceId])}
 private async findByUidPlatform(uid:string,platform:RegisterNotificationTokenInput['platform']):Promise<TokenRow|null>{return ((await this.database.execute(`${TOKEN_SELECT} WHERE uid=? AND platform=? LIMIT 1`,[uid,platform]))[0] as TokenRow)??null}
}
export const userNotificationTokenRepository=new UserNotificationTokenRepository();
function toDomainToken(r:TokenRow):RegisteredNotificationToken{return{id:r.id,uid:r.uid,platform:r.platform,provider:r.provider,deviceId:r.deviceId,token:r.token,locale:r.locale==='en'?'en':'ar',enabled:Boolean(r.enabled),lastSeenAt:r.lastSeenAt??undefined,createdAt:r.createdAt??new Date().toISOString(),updatedAt:r.updatedAt??new Date().toISOString(),deletedAt:r.deletedAt}}
