import { writeFileSync } from "node:fs";
import path from "node:path";

import { readEnvFiles } from "@asol/env-core/files";

import { listCloudflareAccounts, type CloudflareAccount } from "./cloudflare-control";

const CLOUDFLARE_API_BASE_URL = "https://api.cloudflare.com/client/v4";
const PAGE_SIZE = 1000;

type EnvMap = Readonly<Record<string, string | undefined>>;

type R2ObjectSummary = {
  readonly key?: string;
  readonly size?: number;
  readonly last_modified?: string;
};

type CloudflareEnvelope = {
  readonly success?: boolean;
  readonly errors?: readonly { readonly message?: string; readonly code?: number }[];
  readonly result?: readonly R2ObjectSummary[];
  readonly result_info?: {
    readonly cursor?: string;
    readonly is_truncated?: boolean;
  };
};

type R2ContentsSnapshotRow = {
  readonly status: "ok" | "missingCredentials" | "apiError";
  readonly capturedAt: string | null;
  readonly objectCount: number | null;
  readonly totalSizeBytes: number | null;
  readonly latestObjectKey: string | null;
  readonly latestObjectLastModified: string | null;
  readonly message: string | null;
};

function firstPresentEnv(env: EnvMap, ...keys: readonly string[]): string | null {
  for (const key of keys) {
    const value = env[key]?.trim();
    if (value) return value;
  }
  return null;
}

function missing(message: string): R2ContentsSnapshotRow {
  return {
    status: "missingCredentials",
    capturedAt: null,
    objectCount: null,
    totalSizeBytes: null,
    latestObjectKey: null,
    latestObjectLastModified: null,
    message,
  };
}

function apiError(message: string, capturedAt: string): R2ContentsSnapshotRow {
  return {
    status: "apiError",
    capturedAt,
    objectCount: null,
    totalSizeBytes: null,
    latestObjectKey: null,
    latestObjectLastModified: null,
    message,
  };
}

function accountCredentials(account: CloudflareAccount, env: EnvMap): { accountId: string; token: string } | R2ContentsSnapshotRow {
  const accountId = firstPresentEnv(env, account.accountIdEnvVar) ?? account.accountId;
  if (!accountId || accountId.includes("…")) return missing(`Missing ${account.accountIdEnvVar}.`);
  const token = firstPresentEnv(env, account.tokenEnvVar);
  if (!token) return missing(`Missing ${account.tokenEnvVar}.`);
  return { accountId, token };
}

async function readObjectPage(
  account: CloudflareAccount,
  accountId: string,
  token: string,
  cursor: string | null,
): Promise<CloudflareEnvelope> {
  if (!account.bucketName) throw new Error(`Account ${account.id} has no R2 bucket.`);
  const url = new URL(
    `${CLOUDFLARE_API_BASE_URL}/accounts/${accountId}/r2/buckets/${encodeURIComponent(account.bucketName)}/objects`,
  );
  url.searchParams.set("per_page", String(PAGE_SIZE));
  if (cursor) url.searchParams.set("cursor", cursor);
  const response = await fetch(url, {
    headers: { Authorization: `Bearer ${token}` },
  });
  const text = await response.text();
  const payload = text ? (JSON.parse(text) as CloudflareEnvelope) : {};
  if (!response.ok || payload.success === false) {
    const detail = payload.errors?.map((error) => error.message ?? error.code).join("; ") || text;
    throw new Error(detail);
  }
  return payload;
}

async function readAccountContents(account: CloudflareAccount, env: EnvMap, capturedAt: Date): Promise<R2ContentsSnapshotRow> {
  const credentials = accountCredentials(account, env);
  if ("status" in credentials) return credentials;

  let objectCount = 0;
  let totalSizeBytes = 0;
  let latestObjectKey: string | null = null;
  let latestObjectLastModified: string | null = null;
  let cursor: string | null = null;

  do {
    const payload = await readObjectPage(account, credentials.accountId, credentials.token, cursor);
    for (const object of payload.result ?? []) {
      objectCount += 1;
      totalSizeBytes += object.size ?? 0;
      const modified = object.last_modified ?? null;
      if (modified && (!latestObjectLastModified || Date.parse(modified) > Date.parse(latestObjectLastModified))) {
        latestObjectLastModified = modified;
        latestObjectKey = object.key ?? null;
      }
    }
    cursor = payload.result_info?.is_truncated ? payload.result_info.cursor ?? null : null;
  } while (cursor);

  return {
    status: "ok",
    capturedAt: capturedAt.toISOString(),
    objectCount,
    totalSizeBytes,
    latestObjectKey,
    latestObjectLastModified,
    message: null,
  };
}

function generatedHeader(): string {
  return "/**\n" +
    " * Safe Cloudflare R2 bucket contents snapshot for `/dev/cloud-accounts`.\n" +
    " *\n" +
    " * Generated by `npm run cloud-accounts:r2-contents`. It contains object\n" +
    " * counts, byte totals, timestamps, and object keys only: never API tokens,\n" +
    " * S3 access keys, or secret values.\n" +
    " */\n\n";
}

function serializeSnapshot(rows: Record<string, R2ContentsSnapshotRow>): string {
  return generatedHeader() +
    `export type CloudAccountsR2ContentsSnapshotStatus =\n` +
    `  | "ok"\n` +
    `  | "missingCredentials"\n` +
    `  | "apiError";\n\n` +
    `export type CloudAccountsR2ContentsSnapshotRow = {\n` +
    `  readonly status: CloudAccountsR2ContentsSnapshotStatus;\n` +
    `  readonly capturedAt: string | null;\n` +
    `  readonly objectCount: number | null;\n` +
    `  readonly totalSizeBytes: number | null;\n` +
    `  readonly latestObjectKey: string | null;\n` +
    `  readonly latestObjectLastModified: string | null;\n` +
    `  readonly message: string | null;\n` +
    `};\n\n` +
    `export const R2_CONTENTS_SNAPSHOT = ${JSON.stringify(rows, null, 2)} as const satisfies Record<string, CloudAccountsR2ContentsSnapshotRow>;\n`;
}

async function main(): Promise<void> {
  const env = readEnvFiles();
  const capturedAt = new Date();
  const rows: Record<string, R2ContentsSnapshotRow> = {};

  for (const account of listCloudflareAccounts()) {
    try {
      rows[account.id] = await readAccountContents(account, env, capturedAt);
    } catch (error) {
      rows[account.id] = apiError(error instanceof Error ? error.message : String(error), capturedAt.toISOString());
    }
  }

  const outputPath = path.join(
    process.cwd(),
    "src/features/super-admin/presentation/cloud-accounts-r2-contents-snapshot.ts",
  );
  writeFileSync(outputPath, serializeSnapshot(rows), "utf8");
  console.log(`Updated Cloudflare R2 contents snapshot for ${Object.keys(rows).length} account(s).`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
