import { writeFileSync } from "node:fs";
import path from "node:path";

import { USER_PAGE_REGISTRY } from "@asol/simulation-core";
import {
  discoverPageInteractionSources,
  discoverUserPages,
  INTERACTION_BASELINE,
} from "@asol/simulation-core/discovery";

const root = process.cwd();
const entries = discoverUserPages(root).map((page) => {
  const discovery = discoverPageInteractionSources(page, root);
  const registered = USER_PAGE_REGISTRY.find((candidate) => candidate.route === page.route);
  if (!registered) throw new Error(`simulationPageNotRegistered:${page.route}`);
  const eventIds = registered.interactions.map((event) => event.id);
  const previous = INTERACTION_BASELINE[page.route];
  if (
    previous &&
    previous.sourceDigest !== discovery.sourceDigest &&
    previous.eventIds.join("|") === eventIds.join("|")
  ) {
    throw new Error(
      `Interactions changed for ${page.route} but its event registry did not. ` +
        "Add, remove, or rename the matching simulation event before updating the baseline.",
    );
  }
  return [page.route, {
    sourceDigest: discovery.sourceDigest,
    interactionSourceCount: discovery.interactionSourceCount,
    eventIds,
  }] as const;
});

const body = JSON.stringify(Object.fromEntries(entries), null, 2)
  .replace(/"([^"\\]+)":/g, '"$1":');
const output = [
  'import type { InteractionBaseline } from "./discovery.types";',
  "",
  "/** Generated by `npm run simulation:discovery:update`. */",
  `export const INTERACTION_BASELINE: InteractionBaseline = ${body} as const;`,
  "",
].join("\n");

writeFileSync(
  path.join(root, "packages", "simulation-core", "src", "discovery", "interaction-baseline.ts"),
  output,
);
console.log(`Updated simulation interaction baseline for ${entries.length} user pages.`);
