import { writeFileSync } from "node:fs";
import path from "node:path";

import {
  ACCOUNT_DECLARATIONS,
  type AccountDeclaration,
} from "@asol/vercel-deploy-core";
import { readEnvFiles } from "@asol/env-core/files";

import { readVercelAccountUsage } from "../src/features/super-admin/server/services/cloud-accounts-vercel-usage";

function generatedHeader(): string {
  return "/**\n" +
    " * Safe Vercel usage snapshot for `/dev/cloud-accounts`.\n" +
    " *\n" +
    " * Generated by `npm run cloud-accounts:vercel-usage`. It contains numbers and\n" +
    " * labels only: never access tokens or project secrets.\n" +
    " */\n\n";
}

function serializeSnapshot(rows: Record<string, unknown>): string {
  return generatedHeader() +
    `export type CloudAccountsVercelUsageSnapshotStatus =\n` +
    `  | "ok"\n` +
    `  | "missingCredentials"\n` +
    `  | "apiError";\n\n` +
    `export type CloudAccountsVercelUsageSnapshotRow = {\n` +
    `  readonly status: CloudAccountsVercelUsageSnapshotStatus;\n` +
    `  readonly capturedAt: string | null;\n` +
    `  readonly teamSlug: string | null;\n` +
    `  readonly ownerEmail: string | null;\n` +
    `  readonly billingPeriodStart: string | null;\n` +
    `  readonly billingPeriodEnd: string | null;\n` +
    `  readonly planLabel: string | null;\n` +
    `  readonly gitRepository: string | null;\n` +
    `  readonly edgeRequestsLimit: number;\n` +
    `  readonly fastDataTransferBytesLimit: number;\n` +
    `  readonly deploymentsPerDayLimit: number;\n` +
    `  readonly buildsPerHourLimit: number;\n` +
    `  readonly projectsLimit: number;\n` +
    `  readonly runtimeLogsHoursLimit: number;\n` +
    `  readonly functionDurationSecondsLimit: number;\n` +
    `  readonly apiRateLimit: number | null;\n` +
    `  readonly apiRateLimitRemaining: number | null;\n` +
    `  readonly apiRateLimitReset: string | null;\n` +
    `  readonly billedCostUsd: number | null;\n` +
    `  readonly effectiveCostUsd: number | null;\n` +
    `  readonly billingLineCount: number | null;\n` +
    `  readonly topServices: readonly string[];\n` +
    `  readonly metrics: readonly CloudAccountsVercelUsageMetricSnapshot[];\n` +
    `  readonly message: string | null;\n` +
    `};\n\n` +
    `export type CloudAccountsVercelUsageMetricSnapshot = {\n` +
    `  readonly label: string;\n` +
    `  readonly slug: string;\n` +
    `  readonly usedDisplay: string | null;\n` +
    `  readonly limitDisplay: string;\n` +
    `  readonly source: "focusBilling" | "dashboardOnly";\n` +
    `};\n\n` +
    `export const VERCEL_USAGE_SNAPSHOT = ${JSON.stringify(rows, null, 2)} as const satisfies Record<string, CloudAccountsVercelUsageSnapshotRow>;\n`;
}

async function main(): Promise<void> {
  const values = readEnvFiles();
  const capturedAt = new Date().toISOString();
  const snapshot: Record<string, unknown> = {};

  for (const declaration of Object.values(ACCOUNT_DECLARATIONS) as AccountDeclaration[]) {
    snapshot[declaration.name] = await readVercelAccountUsage(declaration, values, capturedAt);
  }

  const outputPath = path.join(
    process.cwd(),
    "src/features/super-admin/presentation/cloud-accounts-vercel-usage-snapshot.ts",
  );
  writeFileSync(outputPath, serializeSnapshot(snapshot), "utf8");
  console.log(`Updated Vercel usage snapshot for ${Object.keys(snapshot).length} account(s).`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
