import { writeFileSync } from "node:fs";
import path from "node:path";

import { readEnvFiles } from "@asol/env-core/files";

import { listTursoOrganizationKeys } from "../src/features/super-admin/server/services/cloud-accounts-turso-organizations";
import { readTursoOrganizationRow } from "../src/features/super-admin/server/services/cloud-accounts-turso-usage";

function serializeSnapshot(rows: Record<string, unknown>): string {
  return "/**\n" +
    " * Safe Turso usage snapshot for `/dev/cloud-accounts`.\n" +
    " *\n" +
    " * Generated by `npm run cloud-accounts:turso-usage` with the same reader the\n" +
    " * live page uses. It holds numbers, plan names, the token owner's login and\n" +
    " * database names only: never tokens, database URLs, or organization secrets.\n" +
    " */\n\n" +
    `import type { TursoCloudAccountUsage } from "./cloud-accounts-facts.types";\n\n` +
    `export const TURSO_USAGE_SNAPSHOT: Readonly<Record<string, TursoCloudAccountUsage>> = ${JSON.stringify(rows, null, 2)};\n`;
}

async function main(): Promise<void> {
  const values = readEnvFiles();
  const capturedAt = new Date().toISOString();
  const snapshot: Record<string, unknown> = {};

  for (const keys of listTursoOrganizationKeys()) {
    const { id, ...row } = await readTursoOrganizationRow(keys, (key) => values[key], capturedAt);
    snapshot[id] = row;
  }

  const outputPath = path.join(
    process.cwd(),
    "src/features/super-admin/presentation/cloud-accounts-turso-usage-snapshot.ts",
  );
  writeFileSync(outputPath, serializeSnapshot(snapshot), "utf8");
  console.log(`Updated Turso usage snapshot for ${Object.keys(snapshot).length} organization(s).`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
