import { writeFileSync } from "node:fs";
import path from "node:path";

import { readEnvFiles } from "@asol/env-core/files";

import { TURSO_CLOUD_ACCOUNTS } from "../src/features/super-admin/presentation/cloud-accounts-reference";

type TursoOrganizationUsage = {
  readonly organization?: {
    readonly usage?: {
      readonly rows_read?: number;
      readonly rows_written?: number;
      readonly storage_bytes?: number;
      readonly bytes_synced?: number;
      readonly databases?: number;
      readonly locations?: number;
      readonly groups?: number;
    };
  };
};

const FREE_LIMITS = {
  rowsRead: 500_000_000,
  rowsWritten: 10_000_000,
  storageBytes: 5_000_000_000,
  bytesSynced: 3_000_000_000,
  databases: 100,
} as const;

const TURSO_ACCOUNT_ENV = {
  hesham106: {
    organization: "TURSO_ORGANIZATION",
    apiToken: "TURSO_API_TOKEN",
  },
  hesham102: {
    organization: "TURSO_NOTIFICATIONS_ORGANIZATION",
    apiToken: "TURSO_NOTIFICATIONS_API_TOKEN",
  },
  hesham103: {
    organization: "TURSO_PRODUCT_ORGANIZATION",
    apiToken: "TURSO_PRODUCT_API_TOKEN",
  },
  hesham104: {
    organization: "TURSO_ORDERS_ORGANIZATION",
    apiToken: "TURSO_ORDERS_API_TOKEN",
  },
  hesham105: {
    organization: "TURSO_PROFILES_ORGANIZATION",
    apiToken: "TURSO_PROFILES_API_TOKEN",
  },
} as const;

function numberOrNull(value: unknown): number | null {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function unavailable(status: "missingCredentials" | "apiError", message: string, capturedAt: string | null) {
  return {
    status,
    capturedAt,
    rowsRead: null,
    rowsReadLimit: FREE_LIMITS.rowsRead,
    rowsWritten: null,
    rowsWrittenLimit: FREE_LIMITS.rowsWritten,
    storageBytes: null,
    storageBytesLimit: FREE_LIMITS.storageBytes,
    bytesSynced: null,
    bytesSyncedLimit: FREE_LIMITS.bytesSynced,
    databases: null,
    databasesLimit: FREE_LIMITS.databases,
    locations: null,
    groups: null,
    message,
  };
}

async function readTursoUsage(
  organization: string,
  apiToken: string,
): Promise<TursoOrganizationUsage> {
  const response = await fetch(
    `https://api.turso.tech/v1/organizations/${encodeURIComponent(organization)}/usage`,
    {
      headers: {
        Authorization: `Bearer ${apiToken}`,
      },
    },
  );
  if (!response.ok) {
    throw new Error(`Turso usage API returned HTTP ${response.status}`);
  }
  return (await response.json()) as TursoOrganizationUsage;
}

function generatedHeader(): string {
  return "/**\n" +
    " * Safe Turso usage snapshot for `/dev/cloud-accounts`.\n" +
    " *\n" +
    " * Generated by `npm run cloud-accounts:turso-usage`. It contains numbers only:\n" +
    " * never tokens, database URLs, or organization secrets.\n" +
    " */\n\n";
}

function serializeSnapshot(rows: Record<string, unknown>): string {
  return generatedHeader() +
    `export type CloudAccountsTursoUsageSnapshotStatus =\n` +
    `  | "ok"\n` +
    `  | "missingCredentials"\n` +
    `  | "apiError";\n\n` +
    `export type CloudAccountsTursoUsageSnapshotRow = {\n` +
    `  readonly status: CloudAccountsTursoUsageSnapshotStatus;\n` +
    `  readonly capturedAt: string | null;\n` +
    `  readonly rowsRead: number | null;\n` +
    `  readonly rowsReadLimit: number;\n` +
    `  readonly rowsWritten: number | null;\n` +
    `  readonly rowsWrittenLimit: number;\n` +
    `  readonly storageBytes: number | null;\n` +
    `  readonly storageBytesLimit: number;\n` +
    `  readonly bytesSynced: number | null;\n` +
    `  readonly bytesSyncedLimit: number;\n` +
    `  readonly databases: number | null;\n` +
    `  readonly databasesLimit: number;\n` +
    `  readonly locations: number | null;\n` +
    `  readonly groups: number | null;\n` +
    `  readonly message: string | null;\n` +
    `};\n\n` +
    `export const TURSO_USAGE_SNAPSHOT = ${JSON.stringify(rows, null, 2)} as const satisfies Record<string, CloudAccountsTursoUsageSnapshotRow>;\n`;
}

async function main(): Promise<void> {
  const values = readEnvFiles();
  const capturedAt = new Date().toISOString();
  const snapshot: Record<string, unknown> = {};

  for (const account of TURSO_CLOUD_ACCOUNTS) {
    const env = TURSO_ACCOUNT_ENV[account.account as keyof typeof TURSO_ACCOUNT_ENV];
    if (!env) {
      snapshot[account.account] = unavailable("missingCredentials", "لا يوجد ربط مفاتيح لهذه المنظمة.", null);
      continue;
    }

    const organization = values[env.organization]?.trim();
    const apiToken = values[env.apiToken]?.trim();
    if (!organization || !apiToken) {
      snapshot[account.account] = unavailable("missingCredentials", "مفاتيح Turso غير موجودة محليًا.", null);
      continue;
    }

    try {
      const data = await readTursoUsage(organization, apiToken);
      const usage = data.organization?.usage ?? {};
      snapshot[account.account] = {
        status: "ok",
        capturedAt,
        rowsRead: numberOrNull(usage.rows_read),
        rowsReadLimit: FREE_LIMITS.rowsRead,
        rowsWritten: numberOrNull(usage.rows_written),
        rowsWrittenLimit: FREE_LIMITS.rowsWritten,
        storageBytes: numberOrNull(usage.storage_bytes),
        storageBytesLimit: FREE_LIMITS.storageBytes,
        bytesSynced: numberOrNull(usage.bytes_synced),
        bytesSyncedLimit: FREE_LIMITS.bytesSynced,
        databases: numberOrNull(usage.databases),
        databasesLimit: FREE_LIMITS.databases,
        locations: numberOrNull(usage.locations),
        groups: numberOrNull(usage.groups),
        message: null,
      };
    } catch (error) {
      snapshot[account.account] = unavailable(
        "apiError",
        error instanceof Error ? error.message : "تعذر جلب استهلاك Turso.",
        capturedAt,
      );
    }
  }

  const outputPath = path.join(
    process.cwd(),
    "src/features/super-admin/presentation/cloud-accounts-turso-usage-snapshot.ts",
  );
  writeFileSync(outputPath, serializeSnapshot(snapshot), "utf8");
  console.log(`Updated Turso usage snapshot for ${Object.keys(snapshot).length} account(s).`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
