PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, order_number TEXT NOT NULL UNIQUE, buyer_id TEXT NOT NULL, order_type TEXT NOT NULL CHECK(order_type IN ('product_order','custom_request_order','mixed_order')), delivery_address_snapshot_json TEXT NOT NULL, currency TEXT NOT NULL CHECK(length(currency)=3), notes TEXT, source TEXT, calculated_status TEXT NOT NULL DEFAULT 'new', subtotal_price INTEGER NOT NULL DEFAULT 0 CHECK(subtotal_price>=0), items_discount_total INTEGER NOT NULL DEFAULT 0 CHECK(items_discount_total>=0), order_discount_total INTEGER NOT NULL DEFAULT 0 CHECK(order_discount_total>=0), shipping_total INTEGER NOT NULL DEFAULT 0 CHECK(shipping_total>=0), shipping_discount_total INTEGER NOT NULL DEFAULT 0 CHECK(shipping_discount_total>=0), tax_total INTEGER NOT NULL DEFAULT 0 CHECK(tax_total>=0), service_fee_total INTEGER NOT NULL DEFAULT 0 CHECK(service_fee_total>=0), platform_fee_total INTEGER NOT NULL DEFAULT 0 CHECK(platform_fee_total>=0), grand_total INTEGER NOT NULL DEFAULT 0 CHECK(grand_total>=0), paid_total INTEGER NOT NULL DEFAULT 0 CHECK(paid_total>=0), refunded_total INTEGER NOT NULL DEFAULT 0 CHECK(refunded_total>=0), remaining_total INTEGER NOT NULL DEFAULT 0 CHECK(remaining_total>=0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, closed_at TEXT, archived_at TEXT);
CREATE TABLE IF NOT EXISTS seller_orders (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, seller_id TEXT NOT NULL, service_provider_id TEXT, seller_order_type TEXT NOT NULL CHECK(seller_order_type IN ('product_items','custom_request','mixed')), status TEXT NOT NULL DEFAULT 'waiting_for_response', seller_subtotal INTEGER NOT NULL DEFAULT 0 CHECK(seller_subtotal>=0), seller_discount_total INTEGER NOT NULL DEFAULT 0 CHECK(seller_discount_total>=0), seller_shipping_total INTEGER NOT NULL DEFAULT 0 CHECK(seller_shipping_total>=0), seller_tax_total INTEGER NOT NULL DEFAULT 0 CHECK(seller_tax_total>=0), seller_commission_total INTEGER NOT NULL DEFAULT 0 CHECK(seller_commission_total>=0), seller_grand_total INTEGER NOT NULL DEFAULT 0 CHECK(seller_grand_total>=0), seller_payout_total INTEGER NOT NULL DEFAULT 0 CHECK(seller_payout_total>=0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, closed_at TEXT, UNIQUE(order_id,seller_id,service_provider_id));
CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, seller_order_id TEXT NOT NULL REFERENCES seller_orders(id) ON DELETE CASCADE, seller_id TEXT NOT NULL, product_id TEXT NOT NULL, variant_id TEXT, product_name_snapshot TEXT NOT NULL, product_description_snapshot TEXT NOT NULL DEFAULT '', product_image_snapshot TEXT, quantity INTEGER NOT NULL CHECK(quantity>0), requires_special_vehicle INTEGER NOT NULL DEFAULT 0, required_vehicle_type TEXT, weight INTEGER CHECK(weight IS NULL OR weight>=0), dimensions_json TEXT, fragile INTEGER NOT NULL DEFAULT 0, requires_refrigeration INTEGER NOT NULL DEFAULT 0, requires_special_loading INTEGER NOT NULL DEFAULT 0, shipping_notes TEXT, unit_price INTEGER NOT NULL CHECK(unit_price>=0), subtotal_price INTEGER NOT NULL DEFAULT 0 CHECK(subtotal_price>=0), item_discount_amount INTEGER NOT NULL DEFAULT 0 CHECK(item_discount_amount>=0), coupon_discount_amount INTEGER NOT NULL DEFAULT 0 CHECK(coupon_discount_amount>=0), shipping_price INTEGER NOT NULL DEFAULT 0 CHECK(shipping_price>=0), shipping_discount_amount INTEGER NOT NULL DEFAULT 0 CHECK(shipping_discount_amount>=0), tax_amount INTEGER NOT NULL DEFAULT 0 CHECK(tax_amount>=0), service_fee_amount INTEGER NOT NULL DEFAULT 0 CHECK(service_fee_amount>=0), commission_amount INTEGER NOT NULL DEFAULT 0 CHECK(commission_amount>=0), total_price INTEGER NOT NULL DEFAULT 0 CHECK(total_price>=0), paid_amount INTEGER NOT NULL DEFAULT 0 CHECK(paid_amount>=0), refunded_amount INTEGER NOT NULL DEFAULT 0 CHECK(refunded_amount>=0), remaining_amount INTEGER NOT NULL DEFAULT 0 CHECK(remaining_amount>=0), status TEXT NOT NULL DEFAULT 'new', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, closed_at TEXT);
CREATE TABLE IF NOT EXISTS custom_request_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, seller_order_id TEXT NOT NULL REFERENCES seller_orders(id) ON DELETE CASCADE, seller_id TEXT, service_provider_id TEXT, title TEXT NOT NULL, buyer_description TEXT NOT NULL, buyer_notes TEXT, requested_quantity INTEGER CHECK(requested_quantity IS NULL OR requested_quantity>0), request_type TEXT NOT NULL CHECK(request_type IN ('pharmacy','supermarket','service','custom_purchase','other')), requires_seller_review_before_pricing INTEGER NOT NULL DEFAULT 1, seller_accepted INTEGER, seller_notes TEXT, seller_provided_description TEXT, available_quantity INTEGER CHECK(available_quantity IS NULL OR available_quantity>=0), suggested_alternatives_json TEXT, requires_buyer_price_approval INTEGER NOT NULL DEFAULT 1, price_offer_expires_at TEXT, requires_special_vehicle INTEGER NOT NULL DEFAULT 0, required_vehicle_type TEXT, estimated_weight INTEGER CHECK(estimated_weight IS NULL OR estimated_weight>=0), estimated_dimensions_json TEXT, fragile INTEGER NOT NULL DEFAULT 0, requires_refrigeration INTEGER NOT NULL DEFAULT 0, requires_special_loading INTEGER NOT NULL DEFAULT 0, shipping_notes TEXT, estimated_price INTEGER CHECK(estimated_price IS NULL OR estimated_price>=0), final_unit_price INTEGER CHECK(final_unit_price IS NULL OR final_unit_price>=0), quantity INTEGER CHECK(quantity IS NULL OR quantity>0), subtotal_price INTEGER NOT NULL DEFAULT 0 CHECK(subtotal_price>=0), discount_amount INTEGER NOT NULL DEFAULT 0 CHECK(discount_amount>=0), shipping_price INTEGER NOT NULL DEFAULT 0 CHECK(shipping_price>=0), shipping_discount_amount INTEGER NOT NULL DEFAULT 0 CHECK(shipping_discount_amount>=0), special_vehicle_fee INTEGER NOT NULL DEFAULT 0 CHECK(special_vehicle_fee>=0), handling_fee INTEGER NOT NULL DEFAULT 0 CHECK(handling_fee>=0), tax_amount INTEGER NOT NULL DEFAULT 0 CHECK(tax_amount>=0), service_fee_amount INTEGER NOT NULL DEFAULT 0 CHECK(service_fee_amount>=0), commission_amount INTEGER NOT NULL DEFAULT 0 CHECK(commission_amount>=0), total_price INTEGER NOT NULL DEFAULT 0 CHECK(total_price>=0), paid_amount INTEGER NOT NULL DEFAULT 0 CHECK(paid_amount>=0), refunded_amount INTEGER NOT NULL DEFAULT 0 CHECK(refunded_amount>=0), remaining_amount INTEGER NOT NULL DEFAULT 0 CHECK(remaining_amount>=0), status TEXT NOT NULL DEFAULT 'new', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, closed_at TEXT);
CREATE TABLE IF NOT EXISTS custom_request_images (id TEXT PRIMARY KEY, custom_request_item_id TEXT NOT NULL REFERENCES custom_request_items(id) ON DELETE CASCADE, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, uploaded_by TEXT NOT NULL, storage_profile_id TEXT NOT NULL DEFAULT 'spicialOrder' CHECK(storage_profile_id='spicialOrder'), image_url TEXT NOT NULL, image_key TEXT NOT NULL, file_name TEXT, file_size INTEGER NOT NULL CHECK(file_size>0 AND file_size<=512000), mime_type TEXT NOT NULL CHECK(mime_type IN ('image/jpeg','image/png','image/webp','image/heic','image/heif')), width INTEGER CHECK(width IS NULL OR width>0), height INTEGER CHECK(height IS NULL OR height>0), image_description TEXT, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shipments (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, direction TEXT NOT NULL DEFAULT 'outbound' CHECK(direction IN ('outbound','return','replacement')), carrier_id TEXT, carrier_company_name TEXT, tracking_number TEXT, shipping_method TEXT NOT NULL, pickup_address_snapshot_json TEXT NOT NULL, delivery_address_snapshot_json TEXT NOT NULL, expected_delivery_at TEXT, contains_special_vehicle_items INTEGER NOT NULL DEFAULT 0, required_vehicle_type TEXT, total_weight INTEGER CHECK(total_weight IS NULL OR total_weight>=0), dimensions_json TEXT, requires_refrigeration INTEGER NOT NULL DEFAULT 0, requires_special_loading INTEGER NOT NULL DEFAULT 0, carrier_notes TEXT, base_shipping_price INTEGER NOT NULL DEFAULT 0 CHECK(base_shipping_price>=0), extra_handling_fee INTEGER NOT NULL DEFAULT 0 CHECK(extra_handling_fee>=0), special_vehicle_fee INTEGER NOT NULL DEFAULT 0 CHECK(special_vehicle_fee>=0), insurance_fee INTEGER NOT NULL DEFAULT 0 CHECK(insurance_fee>=0), shipping_discount_amount INTEGER NOT NULL DEFAULT 0 CHECK(shipping_discount_amount>=0), tax_amount INTEGER NOT NULL DEFAULT 0 CHECK(tax_amount>=0), final_shipping_price INTEGER NOT NULL DEFAULT 0 CHECK(final_shipping_price>=0), status TEXT NOT NULL DEFAULT 'waiting_for_carrier_pickup', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, closed_at TEXT);
CREATE TABLE IF NOT EXISTS shipment_items (id TEXT PRIMARY KEY, shipment_id TEXT NOT NULL REFERENCES shipments(id) ON DELETE CASCADE, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, seller_order_id TEXT NOT NULL REFERENCES seller_orders(id), seller_id TEXT, service_provider_id TEXT, item_type TEXT NOT NULL CHECK(item_type IN ('order_item','custom_request_item')), order_item_id TEXT REFERENCES order_items(id), custom_request_item_id TEXT REFERENCES custom_request_items(id), quantity INTEGER NOT NULL CHECK(quantity>0), status TEXT NOT NULL DEFAULT 'assigned', carrier_received_at TEXT, delivered_at TEXT, notes TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, CHECK((item_type='order_item' AND order_item_id IS NOT NULL AND custom_request_item_id IS NULL) OR (item_type='custom_request_item' AND custom_request_item_id IS NOT NULL AND order_item_id IS NULL)));
CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, buyer_id TEXT NOT NULL, payment_method TEXT NOT NULL CHECK(payment_method IN ('electronic_payment','cash_on_delivery','wallet','bank_transfer')), amount INTEGER NOT NULL CHECK(amount>=0), currency TEXT NOT NULL CHECK(length(currency)=3), status TEXT NOT NULL DEFAULT 'pending', provider TEXT, provider_transaction_id TEXT, transaction_data_json TEXT, paid_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS refunds (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, payment_id TEXT REFERENCES payments(id), order_item_id TEXT REFERENCES order_items(id), custom_request_item_id TEXT REFERENCES custom_request_items(id), return_request_id TEXT REFERENCES return_requests(id), amount INTEGER NOT NULL CHECK(amount>0), currency TEXT NOT NULL CHECK(length(currency)=3), reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'requested', executed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cancellations (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, seller_order_id TEXT REFERENCES seller_orders(id), order_item_id TEXT REFERENCES order_items(id), custom_request_item_id TEXT REFERENCES custom_request_items(id), cancelled_by TEXT NOT NULL, cancelled_by_role TEXT NOT NULL CHECK(cancelled_by_role IN ('buyer','seller','service_provider','carrier','admin','system')), reason TEXT NOT NULL, affected_amount INTEGER NOT NULL DEFAULT 0 CHECK(affected_amount>=0), currency TEXT NOT NULL CHECK(length(currency)=3), requires_refund INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'requested', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cancellation_items (id TEXT PRIMARY KEY, cancellation_id TEXT NOT NULL REFERENCES cancellations(id) ON DELETE CASCADE, order_item_id TEXT REFERENCES order_items(id), custom_request_item_id TEXT REFERENCES custom_request_items(id), amount INTEGER NOT NULL CHECK(amount>=0), created_at TEXT NOT NULL, CHECK((order_item_id IS NULL) != (custom_request_item_id IS NULL)));
CREATE TABLE IF NOT EXISTS return_requests (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, buyer_id TEXT NOT NULL, seller_order_id TEXT REFERENCES seller_orders(id), reason TEXT NOT NULL, seller_approved INTEGER, seller_rejection_reason TEXT, carrier_id TEXT, return_shipment_id TEXT REFERENCES shipments(id), inspection_status TEXT, inspection_notes TEXT, refund_id TEXT REFERENCES refunds(id), status TEXT NOT NULL DEFAULT 'requested', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, closed_at TEXT);
CREATE TABLE IF NOT EXISTS return_request_items (id TEXT PRIMARY KEY, return_request_id TEXT NOT NULL REFERENCES return_requests(id) ON DELETE CASCADE, item_type TEXT NOT NULL CHECK(item_type IN ('order_item','custom_request_item')), order_item_id TEXT REFERENCES order_items(id), custom_request_item_id TEXT REFERENCES custom_request_items(id), quantity INTEGER NOT NULL CHECK(quantity>0), reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, CHECK((item_type='order_item' AND order_item_id IS NOT NULL AND custom_request_item_id IS NULL) OR (item_type='custom_request_item' AND custom_request_item_id IS NOT NULL AND order_item_id IS NULL)));
CREATE TABLE IF NOT EXISTS replacement_requests (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, buyer_id TEXT NOT NULL, seller_order_id TEXT REFERENCES seller_orders(id), reason TEXT NOT NULL, seller_approved INTEGER, seller_rejection_reason TEXT, return_shipment_id TEXT REFERENCES shipments(id), replacement_shipment_id TEXT REFERENCES shipments(id), status TEXT NOT NULL DEFAULT 'requested', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, closed_at TEXT);
CREATE TABLE IF NOT EXISTS replacement_request_items (id TEXT PRIMARY KEY, replacement_request_id TEXT NOT NULL REFERENCES replacement_requests(id) ON DELETE CASCADE, old_item_type TEXT NOT NULL CHECK(old_item_type IN ('order_item','custom_request_item')), old_order_item_id TEXT REFERENCES order_items(id), old_custom_request_item_id TEXT REFERENCES custom_request_items(id), replacement_description TEXT, replacement_product_id TEXT, replacement_variant_id TEXT, quantity INTEGER NOT NULL CHECK(quantity>0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, CHECK((old_item_type='order_item' AND old_order_item_id IS NOT NULL AND old_custom_request_item_id IS NULL) OR (old_item_type='custom_request_item' AND old_custom_request_item_id IS NOT NULL AND old_order_item_id IS NULL)));
CREATE TABLE IF NOT EXISTS disputes (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, seller_order_id TEXT REFERENCES seller_orders(id), order_item_id TEXT REFERENCES order_items(id), custom_request_item_id TEXT REFERENCES custom_request_items(id), shipment_id TEXT REFERENCES shipments(id), return_request_id TEXT REFERENCES return_requests(id), opened_by TEXT NOT NULL, opened_by_role TEXT NOT NULL, reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'opened', admin_decision TEXT, closed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS dispute_messages (id TEXT PRIMARY KEY, dispute_id TEXT NOT NULL REFERENCES disputes(id) ON DELETE CASCADE, sender_id TEXT NOT NULL, sender_role TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_trail (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, old_status TEXT, new_status TEXT, old_value_json TEXT, new_value_json TEXT, performed_by TEXT NOT NULL, performed_by_role TEXT NOT NULL, reason TEXT, source TEXT, ip_address TEXT, notes TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS shipment_items_active_order_item_uq ON shipment_items(order_item_id) WHERE order_item_id IS NOT NULL AND status NOT IN ('rejected_by_carrier','delivered','delivery_rejected','delivery_failed','returned','closed');
CREATE UNIQUE INDEX IF NOT EXISTS shipment_items_active_custom_item_uq ON shipment_items(custom_request_item_id) WHERE custom_request_item_id IS NOT NULL AND status NOT IN ('rejected_by_carrier','delivered','delivery_rejected','delivery_failed','returned','closed');
CREATE UNIQUE INDEX IF NOT EXISTS seller_orders_party_uq ON seller_orders(order_id,seller_id,COALESCE(service_provider_id,''));
CREATE INDEX IF NOT EXISTS orders_buyer_type_status_created_idx ON orders(buyer_id,order_type,calculated_status,created_at); CREATE INDEX IF NOT EXISTS seller_orders_lookup_idx ON seller_orders(order_id,seller_id,service_provider_id,status); CREATE INDEX IF NOT EXISTS order_items_lookup_idx ON order_items(order_id,seller_order_id,seller_id,product_id,status,created_at); CREATE INDEX IF NOT EXISTS custom_items_lookup_idx ON custom_request_items(order_id,seller_order_id,seller_id,service_provider_id,request_type,status,created_at); CREATE INDEX IF NOT EXISTS custom_images_lookup_idx ON custom_request_images(custom_request_item_id,order_id); CREATE INDEX IF NOT EXISTS shipments_lookup_idx ON shipments(order_id,carrier_id,status,tracking_number,created_at); CREATE INDEX IF NOT EXISTS shipment_items_lookup_idx ON shipment_items(shipment_id,order_id,seller_order_id,item_type,status); CREATE INDEX IF NOT EXISTS payments_lookup_idx ON payments(order_id,buyer_id,status); CREATE INDEX IF NOT EXISTS refunds_lookup_idx ON refunds(order_id,payment_id,status); CREATE INDEX IF NOT EXISTS cancellations_lookup_idx ON cancellations(order_id,seller_order_id,status); CREATE INDEX IF NOT EXISTS returns_lookup_idx ON return_requests(order_id,buyer_id,status); CREATE INDEX IF NOT EXISTS replacements_lookup_idx ON replacement_requests(order_id,buyer_id,status); CREATE INDEX IF NOT EXISTS disputes_lookup_idx ON disputes(order_id,status); CREATE INDEX IF NOT EXISTS audit_lookup_idx ON audit_trail(order_id,entity_type,entity_id,performed_by,created_at);
CREATE TRIGGER IF NOT EXISTS orders_status_insert_guard BEFORE INSERT ON orders WHEN NEW.calculated_status NOT IN ('new','waiting_for_seller_response','waiting_for_pricing','processing','partially_fulfilled','fully_fulfilled','partially_cancelled','fully_cancelled','waiting_for_return','waiting_for_replacement','closed','archived') BEGIN SELECT RAISE(ABORT,'invalid order status'); END;
CREATE TRIGGER IF NOT EXISTS orders_status_update_guard BEFORE UPDATE OF calculated_status ON orders WHEN NEW.calculated_status NOT IN ('new','waiting_for_seller_response','waiting_for_pricing','processing','partially_fulfilled','fully_fulfilled','partially_cancelled','fully_cancelled','waiting_for_return','waiting_for_replacement','closed','archived') BEGIN SELECT RAISE(ABORT,'invalid order status'); END;
CREATE TRIGGER IF NOT EXISTS seller_orders_status_guard BEFORE INSERT ON seller_orders WHEN NEW.status NOT IN ('waiting_for_response','waiting_for_pricing','price_offer_sent','buyer_accepted_price','buyer_rejected_price','fully_accepted','partially_accepted','fully_rejected','preparing','ready_for_shipping','handed_to_shipping','partially_fulfilled','fully_fulfilled','cancelled','closed') BEGIN SELECT RAISE(ABORT,'invalid seller order status'); END;
CREATE TRIGGER IF NOT EXISTS order_items_status_guard BEFORE INSERT ON order_items WHEN NEW.status NOT IN ('new','seller_accepted','seller_rejected','buyer_cancelled','admin_cancelled','preparing','ready_for_shipping','assigned_to_shipment','in_transit','delivered','delivery_rejected','return_requested','replacement_requested','returned','refunded','replaced','closed') BEGIN SELECT RAISE(ABORT,'invalid order item status'); END;
CREATE TRIGGER IF NOT EXISTS custom_items_status_guard BEFORE INSERT ON custom_request_items WHEN NEW.status NOT IN ('new','waiting_for_seller_response','waiting_for_pricing','price_offer_sent','buyer_accepted_price','buyer_rejected_price','seller_accepted','seller_rejected','buyer_cancelled','admin_cancelled','preparing','ready_for_shipping','assigned_to_shipment','in_transit','delivered','delivery_rejected','return_requested','replacement_requested','returned','refunded','replaced','closed') BEGIN SELECT RAISE(ABORT,'invalid custom item status'); END;
CREATE TRIGGER IF NOT EXISTS shipments_status_guard BEFORE INSERT ON shipments WHEN NEW.status NOT IN ('waiting_for_carrier_pickup','partially_received_by_carrier','partially_rejected_by_carrier','fully_received_by_carrier','in_transit','arrived_at_distribution_center','out_for_delivery','partially_delivered','fully_delivered','customer_rejected_delivery','delivery_failed','returned','closed') BEGIN SELECT RAISE(ABORT,'invalid shipment status'); END;
CREATE TRIGGER IF NOT EXISTS shipment_items_status_guard BEFORE INSERT ON shipment_items WHEN NEW.status NOT IN ('assigned','received_by_carrier','rejected_by_carrier','in_transit','at_distribution_center','out_for_delivery','delivered','delivery_rejected','delivery_failed','returned','closed') BEGIN SELECT RAISE(ABORT,'invalid shipment item status'); END;
CREATE TRIGGER IF NOT EXISTS payments_status_guard BEFORE INSERT ON payments WHEN NEW.status NOT IN ('pending','partially_paid','fully_paid','failed','cancelled','refunded') BEGIN SELECT RAISE(ABORT,'invalid payment status'); END;
CREATE TRIGGER IF NOT EXISTS refunds_status_guard BEFORE INSERT ON refunds WHEN NEW.status NOT IN ('requested','under_review','accepted','rejected','partially_refunded','fully_refunded') BEGIN SELECT RAISE(ABORT,'invalid refund status'); END;
CREATE TRIGGER IF NOT EXISTS cancellations_status_guard BEFORE INSERT ON cancellations WHEN NEW.status NOT IN ('requested','accepted','rejected','executed') BEGIN SELECT RAISE(ABORT,'invalid cancellation status'); END;
CREATE TRIGGER IF NOT EXISTS returns_status_guard BEFORE INSERT ON return_requests WHEN NEW.status NOT IN ('requested','seller_approved','seller_rejected','waiting_for_pickup','picked_up','received','under_inspection','inspection_accepted','inspection_rejected','refund_pending','refunded','closed') BEGIN SELECT RAISE(ABORT,'invalid return status'); END;
CREATE TRIGGER IF NOT EXISTS replacements_status_guard BEFORE INSERT ON replacement_requests WHEN NEW.status NOT IN ('requested','accepted','rejected','waiting_for_return','return_in_transit','replacement_preparing','replacement_in_transit','replaced','closed') BEGIN SELECT RAISE(ABORT,'invalid replacement status'); END;
CREATE TRIGGER IF NOT EXISTS disputes_status_guard BEFORE INSERT ON disputes WHEN NEW.status NOT IN ('opened','buyer_replied','seller_replied','carrier_replied','admin_intervened','admin_decision_issued','closed') BEGIN SELECT RAISE(ABORT,'invalid dispute status'); END;
CREATE TRIGGER IF NOT EXISTS seller_orders_status_update_guard BEFORE UPDATE OF status ON seller_orders WHEN NEW.status NOT IN ('waiting_for_response','waiting_for_pricing','price_offer_sent','buyer_accepted_price','buyer_rejected_price','fully_accepted','partially_accepted','fully_rejected','preparing','ready_for_shipping','handed_to_shipping','partially_fulfilled','fully_fulfilled','cancelled','closed') BEGIN SELECT RAISE(ABORT,'invalid seller order status'); END;
CREATE TRIGGER IF NOT EXISTS order_items_status_update_guard BEFORE UPDATE OF status ON order_items WHEN NEW.status NOT IN ('new','seller_accepted','seller_rejected','buyer_cancelled','admin_cancelled','preparing','ready_for_shipping','assigned_to_shipment','in_transit','delivered','delivery_rejected','return_requested','replacement_requested','returned','refunded','replaced','closed') BEGIN SELECT RAISE(ABORT,'invalid order item status'); END;
CREATE TRIGGER IF NOT EXISTS custom_items_status_update_guard BEFORE UPDATE OF status ON custom_request_items WHEN NEW.status NOT IN ('new','waiting_for_seller_response','waiting_for_pricing','price_offer_sent','buyer_accepted_price','buyer_rejected_price','seller_accepted','seller_rejected','buyer_cancelled','admin_cancelled','preparing','ready_for_shipping','assigned_to_shipment','in_transit','delivered','delivery_rejected','return_requested','replacement_requested','returned','refunded','replaced','closed') BEGIN SELECT RAISE(ABORT,'invalid custom item status'); END;
CREATE TRIGGER IF NOT EXISTS shipments_status_update_guard BEFORE UPDATE OF status ON shipments WHEN NEW.status NOT IN ('waiting_for_carrier_pickup','partially_received_by_carrier','partially_rejected_by_carrier','fully_received_by_carrier','in_transit','arrived_at_distribution_center','out_for_delivery','partially_delivered','fully_delivered','customer_rejected_delivery','delivery_failed','returned','closed') BEGIN SELECT RAISE(ABORT,'invalid shipment status'); END;
CREATE TRIGGER IF NOT EXISTS shipment_items_status_update_guard BEFORE UPDATE OF status ON shipment_items WHEN NEW.status NOT IN ('assigned','received_by_carrier','rejected_by_carrier','in_transit','at_distribution_center','out_for_delivery','delivered','delivery_rejected','delivery_failed','returned','closed') BEGIN SELECT RAISE(ABORT,'invalid shipment item status'); END;
CREATE TRIGGER IF NOT EXISTS payments_status_update_guard BEFORE UPDATE OF status ON payments WHEN NEW.status NOT IN ('pending','partially_paid','fully_paid','failed','cancelled','refunded') BEGIN SELECT RAISE(ABORT,'invalid payment status'); END;
CREATE TRIGGER IF NOT EXISTS refunds_status_update_guard BEFORE UPDATE OF status ON refunds WHEN NEW.status NOT IN ('requested','under_review','accepted','rejected','partially_refunded','fully_refunded') BEGIN SELECT RAISE(ABORT,'invalid refund status'); END;
CREATE TRIGGER IF NOT EXISTS cancellations_status_update_guard BEFORE UPDATE OF status ON cancellations WHEN NEW.status NOT IN ('requested','accepted','rejected','executed') BEGIN SELECT RAISE(ABORT,'invalid cancellation status'); END;
CREATE TRIGGER IF NOT EXISTS returns_status_update_guard BEFORE UPDATE OF status ON return_requests WHEN NEW.status NOT IN ('requested','seller_approved','seller_rejected','waiting_for_pickup','picked_up','received','under_inspection','inspection_accepted','inspection_rejected','refund_pending','refunded','closed') BEGIN SELECT RAISE(ABORT,'invalid return status'); END;
CREATE TRIGGER IF NOT EXISTS replacements_status_update_guard BEFORE UPDATE OF status ON replacement_requests WHEN NEW.status NOT IN ('requested','accepted','rejected','waiting_for_return','return_in_transit','replacement_preparing','replacement_in_transit','replaced','closed') BEGIN SELECT RAISE(ABORT,'invalid replacement status'); END;
CREATE TRIGGER IF NOT EXISTS disputes_status_update_guard BEFORE UPDATE OF status ON disputes WHEN NEW.status NOT IN ('opened','buyer_replied','seller_replied','carrier_replied','admin_intervened','admin_decision_issued','closed') BEGIN SELECT RAISE(ABORT,'invalid dispute status'); END;
CREATE INDEX IF NOT EXISTS orders_order_number_idx ON orders(order_number); CREATE INDEX IF NOT EXISTS orders_buyer_id_idx ON orders(buyer_id); CREATE INDEX IF NOT EXISTS orders_order_type_idx ON orders(order_type); CREATE INDEX IF NOT EXISTS orders_calculated_status_idx ON orders(calculated_status); CREATE INDEX IF NOT EXISTS orders_created_at_idx ON orders(created_at);
CREATE INDEX IF NOT EXISTS seller_orders_order_id_idx ON seller_orders(order_id); CREATE INDEX IF NOT EXISTS seller_orders_seller_id_idx ON seller_orders(seller_id); CREATE INDEX IF NOT EXISTS seller_orders_service_provider_id_idx ON seller_orders(service_provider_id); CREATE INDEX IF NOT EXISTS seller_orders_status_idx ON seller_orders(status);
CREATE INDEX IF NOT EXISTS order_items_order_id_idx ON order_items(order_id); CREATE INDEX IF NOT EXISTS order_items_seller_order_id_idx ON order_items(seller_order_id); CREATE INDEX IF NOT EXISTS order_items_seller_id_idx ON order_items(seller_id); CREATE INDEX IF NOT EXISTS order_items_product_id_idx ON order_items(product_id); CREATE INDEX IF NOT EXISTS order_items_status_idx ON order_items(status); CREATE INDEX IF NOT EXISTS order_items_created_at_idx ON order_items(created_at);
CREATE INDEX IF NOT EXISTS custom_request_items_order_id_idx ON custom_request_items(order_id); CREATE INDEX IF NOT EXISTS custom_request_items_seller_order_id_idx ON custom_request_items(seller_order_id); CREATE INDEX IF NOT EXISTS custom_request_items_seller_id_idx ON custom_request_items(seller_id); CREATE INDEX IF NOT EXISTS custom_request_items_service_provider_id_idx ON custom_request_items(service_provider_id); CREATE INDEX IF NOT EXISTS custom_request_items_request_type_idx ON custom_request_items(request_type); CREATE INDEX IF NOT EXISTS custom_request_items_status_idx ON custom_request_items(status); CREATE INDEX IF NOT EXISTS custom_request_items_created_at_idx ON custom_request_items(created_at);
CREATE INDEX IF NOT EXISTS custom_request_images_item_idx ON custom_request_images(custom_request_item_id); CREATE INDEX IF NOT EXISTS custom_request_images_order_idx ON custom_request_images(order_id);
CREATE INDEX IF NOT EXISTS shipments_order_id_idx ON shipments(order_id); CREATE INDEX IF NOT EXISTS shipments_carrier_id_idx ON shipments(carrier_id); CREATE INDEX IF NOT EXISTS shipments_status_idx ON shipments(status); CREATE INDEX IF NOT EXISTS shipments_tracking_number_idx ON shipments(tracking_number); CREATE INDEX IF NOT EXISTS shipments_created_at_idx ON shipments(created_at);
CREATE INDEX IF NOT EXISTS shipment_items_shipment_id_idx ON shipment_items(shipment_id); CREATE INDEX IF NOT EXISTS shipment_items_order_id_idx ON shipment_items(order_id); CREATE INDEX IF NOT EXISTS shipment_items_seller_order_id_idx ON shipment_items(seller_order_id); CREATE INDEX IF NOT EXISTS shipment_items_order_item_id_idx ON shipment_items(order_item_id); CREATE INDEX IF NOT EXISTS shipment_items_custom_item_id_idx ON shipment_items(custom_request_item_id); CREATE INDEX IF NOT EXISTS shipment_items_item_type_idx ON shipment_items(item_type); CREATE INDEX IF NOT EXISTS shipment_items_status_idx ON shipment_items(status);
CREATE INDEX IF NOT EXISTS payments_order_id_idx ON payments(order_id); CREATE INDEX IF NOT EXISTS payments_buyer_id_idx ON payments(buyer_id); CREATE INDEX IF NOT EXISTS payments_status_idx ON payments(status); CREATE INDEX IF NOT EXISTS refunds_order_id_idx ON refunds(order_id); CREATE INDEX IF NOT EXISTS refunds_payment_id_idx ON refunds(payment_id); CREATE INDEX IF NOT EXISTS refunds_status_idx ON refunds(status); CREATE INDEX IF NOT EXISTS cancellations_order_id_idx ON cancellations(order_id); CREATE INDEX IF NOT EXISTS cancellations_seller_order_id_idx ON cancellations(seller_order_id); CREATE INDEX IF NOT EXISTS cancellations_status_idx ON cancellations(status);
CREATE INDEX IF NOT EXISTS return_requests_order_id_idx ON return_requests(order_id); CREATE INDEX IF NOT EXISTS return_requests_buyer_id_idx ON return_requests(buyer_id); CREATE INDEX IF NOT EXISTS return_requests_status_idx ON return_requests(status); CREATE INDEX IF NOT EXISTS replacement_requests_order_id_idx ON replacement_requests(order_id); CREATE INDEX IF NOT EXISTS replacement_requests_buyer_id_idx ON replacement_requests(buyer_id); CREATE INDEX IF NOT EXISTS replacement_requests_status_idx ON replacement_requests(status); CREATE INDEX IF NOT EXISTS disputes_order_id_idx ON disputes(order_id); CREATE INDEX IF NOT EXISTS disputes_status_idx ON disputes(status);
CREATE INDEX IF NOT EXISTS audit_trail_order_id_idx ON audit_trail(order_id); CREATE INDEX IF NOT EXISTS audit_trail_entity_type_idx ON audit_trail(entity_type); CREATE INDEX IF NOT EXISTS audit_trail_entity_id_idx ON audit_trail(entity_id); CREATE INDEX IF NOT EXISTS audit_trail_performed_by_idx ON audit_trail(performed_by); CREATE INDEX IF NOT EXISTS audit_trail_created_at_idx ON audit_trail(created_at);
CREATE TRIGGER IF NOT EXISTS audit_role_guard BEFORE INSERT ON audit_trail WHEN NEW.performed_by_role NOT IN ('buyer','seller','service_provider','carrier','admin','system') BEGIN SELECT RAISE(ABORT,'invalid audit actor role'); END;
CREATE TRIGGER IF NOT EXISTS audit_action_guard BEFORE INSERT ON audit_trail WHEN NEW.action NOT IN ('created','updated','status_changed','price_changed','shipping_fee_changed','tracking_updated','accepted','rejected','cancelled','assigned','received','delivered','delivery_rejected','payment_created','refund_requested','refund_executed','return_requested','replacement_requested','dispute_opened','dispute_replied','admin_decision','admin_change','image_uploaded') BEGIN SELECT RAISE(ABORT,'invalid audit action'); END;
CREATE TRIGGER IF NOT EXISTS dispute_actor_role_guard BEFORE INSERT ON disputes WHEN NEW.opened_by_role NOT IN ('buyer','seller','service_provider','carrier','admin','system') BEGIN SELECT RAISE(ABORT,'invalid dispute actor role'); END;
CREATE TRIGGER IF NOT EXISTS dispute_message_role_guard BEFORE INSERT ON dispute_messages WHEN NEW.sender_role NOT IN ('buyer','seller','service_provider','carrier','admin','system') BEGIN SELECT RAISE(ABORT,'invalid dispute message role'); END;
CREATE TRIGGER IF NOT EXISTS orders_money_insert_guard BEFORE INSERT ON orders WHEN typeof(NEW.subtotal_price)<>'integer' OR typeof(NEW.items_discount_total)<>'integer' OR typeof(NEW.order_discount_total)<>'integer' OR typeof(NEW.shipping_total)<>'integer' OR typeof(NEW.shipping_discount_total)<>'integer' OR typeof(NEW.tax_total)<>'integer' OR typeof(NEW.service_fee_total)<>'integer' OR typeof(NEW.platform_fee_total)<>'integer' OR typeof(NEW.grand_total)<>'integer' OR typeof(NEW.paid_total)<>'integer' OR typeof(NEW.refunded_total)<>'integer' OR typeof(NEW.remaining_total)<>'integer' BEGIN SELECT RAISE(ABORT,'order money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS orders_money_update_guard BEFORE UPDATE ON orders WHEN typeof(NEW.subtotal_price)<>'integer' OR typeof(NEW.items_discount_total)<>'integer' OR typeof(NEW.order_discount_total)<>'integer' OR typeof(NEW.shipping_total)<>'integer' OR typeof(NEW.shipping_discount_total)<>'integer' OR typeof(NEW.tax_total)<>'integer' OR typeof(NEW.service_fee_total)<>'integer' OR typeof(NEW.platform_fee_total)<>'integer' OR typeof(NEW.grand_total)<>'integer' OR typeof(NEW.paid_total)<>'integer' OR typeof(NEW.refunded_total)<>'integer' OR typeof(NEW.remaining_total)<>'integer' BEGIN SELECT RAISE(ABORT,'order money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS seller_money_guard BEFORE INSERT ON seller_orders WHEN typeof(NEW.seller_subtotal)<>'integer' OR typeof(NEW.seller_discount_total)<>'integer' OR typeof(NEW.seller_shipping_total)<>'integer' OR typeof(NEW.seller_tax_total)<>'integer' OR typeof(NEW.seller_commission_total)<>'integer' OR typeof(NEW.seller_grand_total)<>'integer' OR typeof(NEW.seller_payout_total)<>'integer' BEGIN SELECT RAISE(ABORT,'seller money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS seller_money_update_guard BEFORE UPDATE ON seller_orders WHEN typeof(NEW.seller_subtotal)<>'integer' OR typeof(NEW.seller_discount_total)<>'integer' OR typeof(NEW.seller_shipping_total)<>'integer' OR typeof(NEW.seller_tax_total)<>'integer' OR typeof(NEW.seller_commission_total)<>'integer' OR typeof(NEW.seller_grand_total)<>'integer' OR typeof(NEW.seller_payout_total)<>'integer' BEGIN SELECT RAISE(ABORT,'seller money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS order_item_money_guard BEFORE INSERT ON order_items WHEN typeof(NEW.unit_price)<>'integer' OR typeof(NEW.subtotal_price)<>'integer' OR typeof(NEW.item_discount_amount)<>'integer' OR typeof(NEW.coupon_discount_amount)<>'integer' OR typeof(NEW.shipping_price)<>'integer' OR typeof(NEW.shipping_discount_amount)<>'integer' OR typeof(NEW.tax_amount)<>'integer' OR typeof(NEW.service_fee_amount)<>'integer' OR typeof(NEW.commission_amount)<>'integer' OR typeof(NEW.total_price)<>'integer' OR typeof(NEW.paid_amount)<>'integer' OR typeof(NEW.refunded_amount)<>'integer' OR typeof(NEW.remaining_amount)<>'integer' BEGIN SELECT RAISE(ABORT,'item money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS order_item_money_update_guard BEFORE UPDATE ON order_items WHEN typeof(NEW.unit_price)<>'integer' OR typeof(NEW.subtotal_price)<>'integer' OR typeof(NEW.item_discount_amount)<>'integer' OR typeof(NEW.coupon_discount_amount)<>'integer' OR typeof(NEW.shipping_price)<>'integer' OR typeof(NEW.shipping_discount_amount)<>'integer' OR typeof(NEW.tax_amount)<>'integer' OR typeof(NEW.service_fee_amount)<>'integer' OR typeof(NEW.commission_amount)<>'integer' OR typeof(NEW.total_price)<>'integer' OR typeof(NEW.paid_amount)<>'integer' OR typeof(NEW.refunded_amount)<>'integer' OR typeof(NEW.remaining_amount)<>'integer' BEGIN SELECT RAISE(ABORT,'item money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS custom_item_money_guard BEFORE INSERT ON custom_request_items WHEN (NEW.estimated_price IS NOT NULL AND typeof(NEW.estimated_price)<>'integer') OR (NEW.final_unit_price IS NOT NULL AND typeof(NEW.final_unit_price)<>'integer') OR typeof(NEW.subtotal_price)<>'integer' OR typeof(NEW.discount_amount)<>'integer' OR typeof(NEW.shipping_price)<>'integer' OR typeof(NEW.shipping_discount_amount)<>'integer' OR typeof(NEW.special_vehicle_fee)<>'integer' OR typeof(NEW.handling_fee)<>'integer' OR typeof(NEW.tax_amount)<>'integer' OR typeof(NEW.service_fee_amount)<>'integer' OR typeof(NEW.commission_amount)<>'integer' OR typeof(NEW.total_price)<>'integer' OR typeof(NEW.paid_amount)<>'integer' OR typeof(NEW.refunded_amount)<>'integer' OR typeof(NEW.remaining_amount)<>'integer' BEGIN SELECT RAISE(ABORT,'custom item money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS custom_item_money_update_guard BEFORE UPDATE ON custom_request_items WHEN (NEW.estimated_price IS NOT NULL AND typeof(NEW.estimated_price)<>'integer') OR (NEW.final_unit_price IS NOT NULL AND typeof(NEW.final_unit_price)<>'integer') OR typeof(NEW.subtotal_price)<>'integer' OR typeof(NEW.discount_amount)<>'integer' OR typeof(NEW.shipping_price)<>'integer' OR typeof(NEW.shipping_discount_amount)<>'integer' OR typeof(NEW.special_vehicle_fee)<>'integer' OR typeof(NEW.handling_fee)<>'integer' OR typeof(NEW.tax_amount)<>'integer' OR typeof(NEW.service_fee_amount)<>'integer' OR typeof(NEW.commission_amount)<>'integer' OR typeof(NEW.total_price)<>'integer' OR typeof(NEW.paid_amount)<>'integer' OR typeof(NEW.refunded_amount)<>'integer' OR typeof(NEW.remaining_amount)<>'integer' BEGIN SELECT RAISE(ABORT,'custom item money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS shipment_money_guard BEFORE INSERT ON shipments WHEN typeof(NEW.base_shipping_price)<>'integer' OR typeof(NEW.extra_handling_fee)<>'integer' OR typeof(NEW.special_vehicle_fee)<>'integer' OR typeof(NEW.insurance_fee)<>'integer' OR typeof(NEW.shipping_discount_amount)<>'integer' OR typeof(NEW.tax_amount)<>'integer' OR typeof(NEW.final_shipping_price)<>'integer' BEGIN SELECT RAISE(ABORT,'shipment money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS shipment_money_update_guard BEFORE UPDATE ON shipments WHEN typeof(NEW.base_shipping_price)<>'integer' OR typeof(NEW.extra_handling_fee)<>'integer' OR typeof(NEW.special_vehicle_fee)<>'integer' OR typeof(NEW.insurance_fee)<>'integer' OR typeof(NEW.shipping_discount_amount)<>'integer' OR typeof(NEW.tax_amount)<>'integer' OR typeof(NEW.final_shipping_price)<>'integer' BEGIN SELECT RAISE(ABORT,'shipment money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS payment_money_guard BEFORE INSERT ON payments WHEN typeof(NEW.amount)<>'integer' BEGIN SELECT RAISE(ABORT,'payment amount must use integer minor units'); END; CREATE TRIGGER IF NOT EXISTS refund_money_guard BEFORE INSERT ON refunds WHEN typeof(NEW.amount)<>'integer' BEGIN SELECT RAISE(ABORT,'refund amount must use integer minor units'); END; CREATE TRIGGER IF NOT EXISTS cancellation_money_guard BEFORE INSERT ON cancellations WHEN typeof(NEW.affected_amount)<>'integer' BEGIN SELECT RAISE(ABORT,'cancellation amount must use integer minor units'); END; CREATE TRIGGER IF NOT EXISTS cancellation_item_money_guard BEFORE INSERT ON cancellation_items WHEN typeof(NEW.amount)<>'integer' BEGIN SELECT RAISE(ABORT,'cancellation item amount must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS payment_money_update_guard BEFORE UPDATE OF amount ON payments WHEN typeof(NEW.amount)<>'integer' BEGIN SELECT RAISE(ABORT,'payment amount must use integer minor units'); END; CREATE TRIGGER IF NOT EXISTS refund_money_update_guard BEFORE UPDATE OF amount ON refunds WHEN typeof(NEW.amount)<>'integer' BEGIN SELECT RAISE(ABORT,'refund amount must use integer minor units'); END; CREATE TRIGGER IF NOT EXISTS cancellation_money_update_guard BEFORE UPDATE OF affected_amount ON cancellations WHEN typeof(NEW.affected_amount)<>'integer' BEGIN SELECT RAISE(ABORT,'cancellation amount must use integer minor units'); END; CREATE TRIGGER IF NOT EXISTS cancellation_item_money_update_guard BEFORE UPDATE OF amount ON cancellation_items WHEN typeof(NEW.amount)<>'integer' BEGIN SELECT RAISE(ABORT,'cancellation item amount must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS custom_request_requires_image_guard BEFORE UPDATE OF status ON custom_request_items WHEN NEW.status IN ('waiting_for_pricing','price_offer_sent','buyer_accepted_price','seller_accepted','preparing','ready_for_shipping','assigned_to_shipment','in_transit','delivered','return_requested','replacement_requested','returned','refunded','replaced','closed') AND NOT EXISTS (SELECT 1 FROM custom_request_images WHERE custom_request_item_id=NEW.id) BEGIN SELECT RAISE(ABORT,'custom request requires at least one image'); END;
CREATE TRIGGER IF NOT EXISTS custom_image_order_guard BEFORE INSERT ON custom_request_images WHEN NOT EXISTS (SELECT 1 FROM custom_request_items WHERE id=NEW.custom_request_item_id AND order_id=NEW.order_id) BEGIN SELECT RAISE(ABORT,'custom image order mismatch'); END;
CREATE TRIGGER IF NOT EXISTS shipment_item_consistency_guard BEFORE INSERT ON shipment_items WHEN NOT EXISTS (SELECT 1 FROM shipments WHERE id=NEW.shipment_id AND order_id=NEW.order_id) OR NOT EXISTS (SELECT 1 FROM seller_orders WHERE id=NEW.seller_order_id AND order_id=NEW.order_id) OR (NEW.item_type='order_item' AND NOT EXISTS (SELECT 1 FROM order_items WHERE id=NEW.order_item_id AND order_id=NEW.order_id AND seller_order_id=NEW.seller_order_id)) OR (NEW.item_type='custom_request_item' AND NOT EXISTS (SELECT 1 FROM custom_request_items WHERE id=NEW.custom_request_item_id AND order_id=NEW.order_id AND seller_order_id=NEW.seller_order_id)) BEGIN SELECT RAISE(ABORT,'shipment item relationship mismatch'); END;

CREATE TABLE IF NOT EXISTS shipping_quotes (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  seller_order_id TEXT NOT NULL REFERENCES seller_orders(id) ON DELETE CASCADE,
  seller_id TEXT NOT NULL,
  service_provider_id TEXT,
  buyer_id TEXT NOT NULL,
  version INTEGER NOT NULL CHECK(version > 0),
  proposed_by TEXT,
  proposed_by_role TEXT CHECK(proposed_by_role IS NULL OR proposed_by_role IN ('seller','service_provider','admin')),
  base_shipping_price INTEGER NOT NULL DEFAULT 0 CHECK(base_shipping_price >= 0),
  special_vehicle_fee INTEGER NOT NULL DEFAULT 0 CHECK(special_vehicle_fee >= 0),
  total_shipping_price INTEGER NOT NULL DEFAULT 0 CHECK(total_shipping_price >= 0),
  status TEXT NOT NULL CHECK(status IN ('requested','pending_buyer','accepted','rejected','superseded','expired','cancelled')),
  notes TEXT,
  expires_at TEXT,
  responded_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(seller_order_id, version)
);
CREATE INDEX IF NOT EXISTS shipping_quotes_order_id_idx ON shipping_quotes(order_id);
CREATE INDEX IF NOT EXISTS shipping_quotes_seller_order_id_idx ON shipping_quotes(seller_order_id);
CREATE INDEX IF NOT EXISTS shipping_quotes_buyer_id_idx ON shipping_quotes(buyer_id);
CREATE INDEX IF NOT EXISTS shipping_quotes_status_idx ON shipping_quotes(status);
CREATE UNIQUE INDEX IF NOT EXISTS shipping_quotes_one_pending_idx ON shipping_quotes(seller_order_id) WHERE status='pending_buyer';
CREATE UNIQUE INDEX IF NOT EXISTS shipping_quotes_one_accepted_idx ON shipping_quotes(seller_order_id) WHERE status='accepted';
CREATE TRIGGER IF NOT EXISTS shipping_quote_money_insert_guard BEFORE INSERT ON shipping_quotes WHEN typeof(NEW.base_shipping_price)<>'integer' OR typeof(NEW.special_vehicle_fee)<>'integer' OR typeof(NEW.total_shipping_price)<>'integer' BEGIN SELECT RAISE(ABORT,'shipping quote money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS shipping_quote_money_update_guard BEFORE UPDATE OF base_shipping_price,special_vehicle_fee,total_shipping_price ON shipping_quotes WHEN typeof(NEW.base_shipping_price)<>'integer' OR typeof(NEW.special_vehicle_fee)<>'integer' OR typeof(NEW.total_shipping_price)<>'integer' BEGIN SELECT RAISE(ABORT,'shipping quote money must use integer minor units'); END;

CREATE TABLE IF NOT EXISTS delivery_plans (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
  buyer_id TEXT NOT NULL,
  strategy TEXT NOT NULL DEFAULT 'unified' CHECK(strategy IN ('unified','hybrid','separate')),
  status TEXT NOT NULL DEFAULT 'collecting_quotes' CHECK(status IN ('collecting_quotes','pending_buyer','accepted','reprice_required','separate_selected','cancelled','completed')),
  selected_quote_id TEXT,
  fallback_confirmed_price INTEGER NOT NULL DEFAULT 0 CHECK(fallback_confirmed_price >= 0),
  fallback_has_pending_quotes INTEGER NOT NULL DEFAULT 0 CHECK(fallback_has_pending_quotes IN (0,1)),
  fallback_available INTEGER NOT NULL DEFAULT 1 CHECK(fallback_available IN (0,1)),
  special_vehicle_required INTEGER NOT NULL DEFAULT 0 CHECK(special_vehicle_required IN (0,1)),
  seller_count INTEGER NOT NULL CHECK(seller_count >= 0),
  currency TEXT NOT NULL CHECK(length(currency)=3),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS delivery_plan_stops (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES delivery_plans(id) ON DELETE CASCADE,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  seller_order_id TEXT NOT NULL REFERENCES seller_orders(id) ON DELETE CASCADE,
  seller_id TEXT NOT NULL,
  original_carrier_id TEXT,
  pickup_address_snapshot_json TEXT NOT NULL,
  requires_location_quote INTEGER NOT NULL DEFAULT 0 CHECK(requires_location_quote IN (0,1)),
  fallback_shipping_price INTEGER NOT NULL DEFAULT 0 CHECK(fallback_shipping_price >= 0),
  fallback_special_vehicle_fee INTEGER NOT NULL DEFAULT 0 CHECK(fallback_special_vehicle_fee >= 0),
  pickup_sequence INTEGER NOT NULL DEFAULT 0 CHECK(pickup_sequence >= 0),
  status TEXT NOT NULL DEFAULT 'waiting' CHECK(status IN ('waiting','ready','collected','skipped','cancelled')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(plan_id, seller_order_id)
);
CREATE TABLE IF NOT EXISTS delivery_plan_candidates (
  plan_id TEXT NOT NULL REFERENCES delivery_plans(id) ON DELETE CASCADE,
  provider_id TEXT NOT NULL,
  source TEXT NOT NULL CHECK(source IN ('linked','qualified_network','admin')),
  coverage_score INTEGER NOT NULL DEFAULT 0 CHECK(coverage_score >= 0),
  status TEXT NOT NULL DEFAULT 'invited' CHECK(status IN ('invited','viewed','declined','quoted')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(plan_id, provider_id)
);
CREATE TABLE IF NOT EXISTS delivery_plan_candidate_stops (
  plan_id TEXT NOT NULL,
  provider_id TEXT NOT NULL,
  stop_id TEXT NOT NULL REFERENCES delivery_plan_stops(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY(plan_id, provider_id, stop_id),
  FOREIGN KEY(plan_id, provider_id) REFERENCES delivery_plan_candidates(plan_id, provider_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS delivery_plan_quotes (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES delivery_plans(id) ON DELETE CASCADE,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  provider_id TEXT NOT NULL,
  version INTEGER NOT NULL CHECK(version > 0),
  base_shipping_price INTEGER NOT NULL DEFAULT 0 CHECK(base_shipping_price >= 0),
  special_vehicle_fee INTEGER NOT NULL DEFAULT 0 CHECK(special_vehicle_fee >= 0),
  total_shipping_price INTEGER NOT NULL DEFAULT 0 CHECK(total_shipping_price >= 0),
  status TEXT NOT NULL CHECK(status IN ('pending_buyer','accepted','rejected','superseded','withdrawn','expired')),
  notes TEXT,
  expires_at TEXT,
  responded_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(plan_id, provider_id, version)
);
CREATE TABLE IF NOT EXISTS delivery_plan_quote_stops (
  quote_id TEXT NOT NULL REFERENCES delivery_plan_quotes(id) ON DELETE CASCADE,
  plan_id TEXT NOT NULL REFERENCES delivery_plans(id) ON DELETE CASCADE,
  stop_id TEXT NOT NULL REFERENCES delivery_plan_stops(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY(quote_id, stop_id)
);
CREATE TABLE IF NOT EXISTS delivery_plan_shipments (
  plan_id TEXT NOT NULL REFERENCES delivery_plans(id) ON DELETE CASCADE,
  shipment_id TEXT NOT NULL UNIQUE REFERENCES shipments(id) ON DELETE CASCADE,
  quote_id TEXT REFERENCES delivery_plan_quotes(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY(plan_id, shipment_id)
);
CREATE INDEX IF NOT EXISTS delivery_plans_order_id_idx ON delivery_plans(order_id);
CREATE INDEX IF NOT EXISTS delivery_plans_buyer_id_idx ON delivery_plans(buyer_id);
CREATE INDEX IF NOT EXISTS delivery_plans_status_idx ON delivery_plans(status);
CREATE INDEX IF NOT EXISTS delivery_plan_stops_plan_id_idx ON delivery_plan_stops(plan_id);
CREATE INDEX IF NOT EXISTS delivery_plan_stops_seller_order_idx ON delivery_plan_stops(seller_order_id);
CREATE INDEX IF NOT EXISTS delivery_plan_candidates_provider_idx ON delivery_plan_candidates(provider_id);
CREATE INDEX IF NOT EXISTS delivery_plan_candidate_stops_stop_idx ON delivery_plan_candidate_stops(stop_id);
CREATE INDEX IF NOT EXISTS delivery_plan_quotes_plan_id_idx ON delivery_plan_quotes(plan_id);
CREATE INDEX IF NOT EXISTS delivery_plan_quotes_provider_id_idx ON delivery_plan_quotes(provider_id);
CREATE INDEX IF NOT EXISTS delivery_plan_quotes_status_idx ON delivery_plan_quotes(status);
CREATE INDEX IF NOT EXISTS delivery_plan_quote_stops_stop_idx ON delivery_plan_quote_stops(stop_id);
CREATE UNIQUE INDEX IF NOT EXISTS delivery_plan_quotes_one_pending_provider_idx ON delivery_plan_quotes(plan_id,provider_id) WHERE status='pending_buyer';
CREATE TRIGGER IF NOT EXISTS delivery_plan_money_insert_guard BEFORE INSERT ON delivery_plans WHEN typeof(NEW.fallback_confirmed_price)<>'integer' BEGIN SELECT RAISE(ABORT,'delivery plan money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS delivery_plan_money_update_guard BEFORE UPDATE OF fallback_confirmed_price ON delivery_plans WHEN typeof(NEW.fallback_confirmed_price)<>'integer' BEGIN SELECT RAISE(ABORT,'delivery plan money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS delivery_plan_stop_money_insert_guard BEFORE INSERT ON delivery_plan_stops WHEN typeof(NEW.fallback_shipping_price)<>'integer' OR typeof(NEW.fallback_special_vehicle_fee)<>'integer' BEGIN SELECT RAISE(ABORT,'delivery plan stop money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS delivery_plan_quote_money_insert_guard BEFORE INSERT ON delivery_plan_quotes WHEN typeof(NEW.base_shipping_price)<>'integer' OR typeof(NEW.special_vehicle_fee)<>'integer' OR typeof(NEW.total_shipping_price)<>'integer' BEGIN SELECT RAISE(ABORT,'delivery plan quote money must use integer minor units'); END;
CREATE TRIGGER IF NOT EXISTS delivery_plan_quote_money_update_guard BEFORE UPDATE OF base_shipping_price,special_vehicle_fee,total_shipping_price ON delivery_plan_quotes WHEN typeof(NEW.base_shipping_price)<>'integer' OR typeof(NEW.special_vehicle_fee)<>'integer' OR typeof(NEW.total_shipping_price)<>'integer' BEGIN SELECT RAISE(ABORT,'delivery plan quote money must use integer minor units'); END;
