CREATE TABLE `products` (
  `id` text PRIMARY KEY NOT NULL,
  `uid` text NOT NULL,
  `main_category_id` text NOT NULL,
  `subcategory_id` text NOT NULL,
  `main_name` text NOT NULL DEFAULT '',
  `main_brand` text NOT NULL DEFAULT '',
  `main_manufacturer` text NOT NULL DEFAULT '',
  `main_available` integer NOT NULL DEFAULT 1,
  `main_description` text NOT NULL DEFAULT '',
  `price_current` text NOT NULL DEFAULT '',
  `price_before_discount` text NOT NULL DEFAULT '',
  `price_label` text NOT NULL DEFAULT '',
  `price_needs_car` integer NOT NULL DEFAULT 0,
  `spec_color` text NOT NULL DEFAULT '',
  `spec_dimensions` text NOT NULL DEFAULT '',
  `spec_condition` text NOT NULL DEFAULT '',
  `spec_size` text NOT NULL DEFAULT '',
  `spec_weight` text NOT NULL DEFAULT '',
  `spec_year` text NOT NULL DEFAULT '',
  `vehicle_brand` text NOT NULL DEFAULT '',
  `vehicle_body_type` text NOT NULL DEFAULT '',
  `vehicle_fuel` text NOT NULL DEFAULT '',
  `vehicle_transmission` text NOT NULL DEFAULT '',
  `vehicle_special` text NOT NULL DEFAULT '',
  `property_area` text NOT NULL DEFAULT '',
  `property_rooms` text NOT NULL DEFAULT '',
  `property_bathrooms` text NOT NULL DEFAULT '',
  `property_type` text NOT NULL DEFAULT '',
  `property_address` text NOT NULL DEFAULT '',
  `property_latitude` text NOT NULL DEFAULT '',
  `property_longitude` text NOT NULL DEFAULT '',
  `property_finishing` text NOT NULL DEFAULT '',
  `pharmacy_catalog_kind` text NOT NULL DEFAULT '',
  `pharmacy_catalog_category_id` text NOT NULL DEFAULT '',
  `pharmacy_catalog_category_name_ar` text NOT NULL DEFAULT '',
  `pharmacy_catalog_category_name_en` text NOT NULL DEFAULT '',
  `pharmacy_catalog_subcategory_id` text NOT NULL DEFAULT '',
  `pharmacy_catalog_subcategory_name_ar` text NOT NULL DEFAULT '',
  `pharmacy_catalog_subcategory_name_en` text NOT NULL DEFAULT '',
  `pharmacy_catalog_fixed_product_id` text NOT NULL DEFAULT '',
  `pharmacy_category_id` text NOT NULL DEFAULT '',
  `pharmacy_category` text NOT NULL DEFAULT '',
  `pharmacy_subcategory_id` text NOT NULL DEFAULT '',
  `pharmacy_subcategory` text NOT NULL DEFAULT '',
  `pharmacy_active_ingredient_id` text NOT NULL DEFAULT '',
  `pharmacy_active_ingredient` text NOT NULL DEFAULT '',
  `pharmacy_name_ar` text NOT NULL DEFAULT '',
  `pharmacy_name_en` text NOT NULL DEFAULT '',
  `pharmacy_form_id` text NOT NULL DEFAULT '',
  `pharmacy_form` text NOT NULL DEFAULT '',
  `pharmacy_concentration_id` text NOT NULL DEFAULT '',
  `pharmacy_concentration` text NOT NULL DEFAULT '',
  `pharmacy_prescription_required` integer NOT NULL DEFAULT 0,
  `rating_value` text NOT NULL DEFAULT '',
  `rating_comment` text NOT NULL DEFAULT '',
  `rating_enabled` integer NOT NULL DEFAULT 1,
  `rating_target_enabled` integer NOT NULL DEFAULT 1,
  `rating_mode` text NOT NULL DEFAULT '',
  `images_json` text NOT NULL DEFAULT '[]',
  `status` text NOT NULL DEFAULT 'active' CHECK (`status` IN ('draft', 'active', 'archived')),
  `created_at` text NOT NULL,
  `updated_at` text NOT NULL
);--> statement-breakpoint
CREATE INDEX `products_uid_idx` ON `products` (`uid`);--> statement-breakpoint
CREATE INDEX `products_category_idx` ON `products` (`main_category_id`, `subcategory_id`);
