/**
 * Safe Turso usage snapshot for `/dev/cloud-accounts`.
 *
 * Generated by `npm run cloud-accounts:turso-usage`. It contains numbers only:
 * never tokens, database URLs, or organization secrets.
 */

export type CloudAccountsTursoUsageSnapshotStatus =
  | "ok"
  | "missingCredentials"
  | "apiError";

export type CloudAccountsTursoUsageSnapshotRow = {
  readonly status: CloudAccountsTursoUsageSnapshotStatus;
  readonly capturedAt: string | null;
  readonly rowsRead: number | null;
  readonly rowsReadLimit: number;
  readonly rowsWritten: number | null;
  readonly rowsWrittenLimit: number;
  readonly storageBytes: number | null;
  readonly storageBytesLimit: number;
  readonly bytesSynced: number | null;
  readonly bytesSyncedLimit: number;
  readonly databases: number | null;
  readonly databasesLimit: number;
  readonly locations: number | null;
  readonly groups: number | null;
  readonly message: string | null;
};

export const TURSO_USAGE_SNAPSHOT = {
  "hesham106": {
    "status": "ok",
    "capturedAt": "2026-09-08T03:59:15.937Z",
    "rowsRead": 311,
    "rowsReadLimit": 500000000,
    "rowsWritten": 64,
    "rowsWrittenLimit": 10000000,
    "storageBytes": 180224,
    "storageBytesLimit": 5000000000,
    "bytesSynced": 0,
    "bytesSyncedLimit": 3000000000,
    "databases": 3,
    "databasesLimit": 100,
    "locations": 4,
    "groups": 0,
    "message": null
  },
  "hesham102": {
    "status": "ok",
    "capturedAt": "2026-09-08T03:59:15.937Z",
    "rowsRead": 1081,
    "rowsReadLimit": 500000000,
    "rowsWritten": 227,
    "rowsWrittenLimit": 10000000,
    "storageBytes": 40960,
    "storageBytesLimit": 5000000000,
    "bytesSynced": 0,
    "bytesSyncedLimit": 3000000000,
    "databases": 1,
    "databasesLimit": 100,
    "locations": 2,
    "groups": 0,
    "message": null
  },
  "hesham103": {
    "status": "ok",
    "capturedAt": "2026-09-08T03:59:15.937Z",
    "rowsRead": 2766,
    "rowsReadLimit": 500000000,
    "rowsWritten": 0,
    "rowsWrittenLimit": 10000000,
    "storageBytes": 126976,
    "storageBytesLimit": 5000000000,
    "bytesSynced": 0,
    "bytesSyncedLimit": 3000000000,
    "databases": 1,
    "databasesLimit": 100,
    "locations": 2,
    "groups": 0,
    "message": null
  },
  "hesham104": {
    "status": "ok",
    "capturedAt": "2026-09-08T03:59:15.937Z",
    "rowsRead": 13671,
    "rowsReadLimit": 500000000,
    "rowsWritten": 138,
    "rowsWrittenLimit": 10000000,
    "storageBytes": 765952,
    "storageBytesLimit": 5000000000,
    "bytesSynced": 0,
    "bytesSyncedLimit": 3000000000,
    "databases": 9,
    "databasesLimit": 100,
    "locations": 4,
    "groups": 0,
    "message": null
  },
  "hesham105": {
    "status": "ok",
    "capturedAt": "2026-09-08T03:59:15.937Z",
    "rowsRead": 11759,
    "rowsReadLimit": 500000000,
    "rowsWritten": 75,
    "rowsWrittenLimit": 10000000,
    "storageBytes": 311296,
    "storageBytesLimit": 5000000000,
    "bytesSynced": 0,
    "bytesSyncedLimit": 3000000000,
    "databases": 7,
    "databasesLimit": 100,
    "locations": 4,
    "groups": 0,
    "message": null
  }
} as const satisfies Record<string, CloudAccountsTursoUsageSnapshotRow>;
