/**
 * Safe Cloudflare R2 usage snapshot for `/dev/cloud-accounts`.
 *
 * Generated by `npm run cloud-accounts:r2-usage`. It contains numbers and
 * labels only: never API tokens, S3 access keys, or secret values.
 */

export type CloudAccountsR2UsageSnapshotStatus =
  | "ok"
  | "missingCredentials"
  | "apiError";

export type CloudAccountsR2UsageSnapshotRow = {
  readonly status: CloudAccountsR2UsageSnapshotStatus;
  readonly capturedAt: string | null;
  readonly periodStart: string | null;
  readonly periodEnd: string | null;
  readonly classAOperations: number | null;
  readonly classAOperationsLimit: number;
  readonly classBOperations: number | null;
  readonly classBOperationsLimit: number;
  readonly storageBytes: number | null;
  readonly storageBytesLimit: number;
  readonly objectCount: number | null;
  readonly uploadCount: number | null;
  readonly operationTypes: readonly string[];
  readonly message: string | null;
};

export const R2_USAGE_SNAPSHOT = {
  "general": {
    "status": "ok",
    "capturedAt": "2026-09-08T04:28:00.000Z",
    "periodStart": "2026-09-01T00:00:00.000Z",
    "periodEnd": "2026-09-08T04:28:00.000Z",
    "classAOperations": 276,
    "classAOperationsLimit": 1000000,
    "classBOperations": 56333,
    "classBOperationsLimit": 10000000,
    "storageBytes": 863652,
    "storageBytesLimit": 10000000000,
    "objectCount": 14,
    "uploadCount": 0,
    "operationTypes": [
      "ListObjects:54794",
      "HeadBucket:2",
      "HeadObject:807",
      "PutBucketCors:3",
      "GetBucketCors:38",
      "PutObject:273",
      "ListMultipartUploads:1",
      "GetObject:691"
    ],
    "message": "Captured through the connected Cloudflare account in Codex; local API token still lacks GraphQL Analytics access. Latest refresh: not authorized for that account. Latest refresh: not authorized for that account. Latest refresh: not authorized for that account."
  },
  "products": {
    "status": "apiError",
    "capturedAt": "2026-09-09T04:38:40.962Z",
    "periodStart": "2026-09-01T00:00:00.000Z",
    "periodEnd": "2026-09-09T04:38:40.962Z",
    "classAOperations": null,
    "classAOperationsLimit": 1000000,
    "classBOperations": null,
    "classBOperationsLimit": 10000000,
    "storageBytes": null,
    "storageBytesLimit": 10000000000,
    "objectCount": null,
    "uploadCount": null,
    "operationTypes": [],
    "message": "not authorized for that account"
  },
  "products-apparel-pets": {
    "status": "apiError",
    "capturedAt": "2026-09-09T04:38:40.962Z",
    "periodStart": "2026-09-01T00:00:00.000Z",
    "periodEnd": "2026-09-09T04:38:40.962Z",
    "classAOperations": null,
    "classAOperationsLimit": 1000000,
    "classBOperations": null,
    "classBOperationsLimit": 10000000,
    "storageBytes": null,
    "storageBytesLimit": 10000000000,
    "objectCount": null,
    "uploadCount": null,
    "operationTypes": [],
    "message": "not authorized for that account"
  },
  "ota": {
    "status": "missingCredentials",
    "capturedAt": null,
    "periodStart": null,
    "periodEnd": null,
    "classAOperations": null,
    "classAOperationsLimit": 1000000,
    "classBOperations": null,
    "classBOperationsLimit": 10000000,
    "storageBytes": null,
    "storageBytesLimit": 10000000000,
    "objectCount": null,
    "uploadCount": null,
    "operationTypes": [],
    "message": "مفتاح Cloudflare API غير موجود محليًا."
  }
} as const satisfies Record<string, CloudAccountsR2UsageSnapshotRow>;
