/**
 * Safe Vercel usage snapshot for `/dev/cloud-accounts`.
 *
 * Generated by `npm run cloud-accounts:vercel-usage`. It contains numbers and
 * labels only: never access tokens or project secrets.
 */

export type CloudAccountsVercelUsageSnapshotStatus =
  | "ok"
  | "missingCredentials"
  | "apiError";

export type CloudAccountsVercelUsageSnapshotRow = {
  readonly status: CloudAccountsVercelUsageSnapshotStatus;
  readonly capturedAt: string | null;
  readonly teamSlug: string | null;
  readonly ownerEmail: string | null;
  readonly billingPeriodStart: string | null;
  readonly billingPeriodEnd: string | null;
  readonly planLabel: string | null;
  readonly gitRepository: string | null;
  readonly edgeRequestsLimit: number;
  readonly fastDataTransferBytesLimit: number;
  readonly deploymentsPerDayLimit: number;
  readonly buildsPerHourLimit: number;
  readonly projectsLimit: number;
  readonly runtimeLogsHoursLimit: number;
  readonly functionDurationSecondsLimit: number;
  readonly apiRateLimit: number | null;
  readonly apiRateLimitRemaining: number | null;
  readonly apiRateLimitReset: string | null;
  readonly billedCostUsd: number | null;
  readonly effectiveCostUsd: number | null;
  readonly billingLineCount: number | null;
  readonly topServices: readonly string[];
  readonly metrics: readonly CloudAccountsVercelUsageMetricSnapshot[];
  readonly message: string | null;
};

export type CloudAccountsVercelUsageMetricSnapshot = {
  readonly label: string;
  readonly slug: string;
  readonly usedDisplay: string | null;
  readonly limitDisplay: string;
  readonly source: "focusBilling" | "dashboardOnly";
};

export const VERCEL_USAGE_SNAPSHOT = {
  "gova": {
    "status": "ok",
    "capturedAt": "2026-09-18T12:05:47.764Z",
    "teamSlug": "hesham-101",
    "ownerEmail": "print.code.1000@gmail.com",
    "planLabel": "hobby",
    "gitRepository": null,
    "billingPeriodStart": "2026-09-01T00:00:00.000Z",
    "billingPeriodEnd": "2026-09-18T12:05:47.764Z",
    "edgeRequestsLimit": 1000000,
    "fastDataTransferBytesLimit": 100000000000,
    "deploymentsPerDayLimit": 100,
    "buildsPerHourLimit": 100,
    "projectsLimit": 200,
    "runtimeLogsHoursLimit": 1,
    "functionDurationSecondsLimit": 300,
    "apiRateLimit": 400,
    "apiRateLimitRemaining": 399,
    "apiRateLimitReset": "2026-09-18T12:06:51.000Z",
    "billedCostUsd": null,
    "effectiveCostUsd": null,
    "billingLineCount": null,
    "topServices": [],
    "metrics": [
      {
        "label": "Snapshot Storage",
        "slug": "snapshot-storage",
        "usedDisplay": null,
        "limitDisplay": "15 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Active CPU",
        "slug": "vercel-functions-fluid-cpu-duration",
        "usedDisplay": null,
        "limitDisplay": "4h / 16h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Active CPU",
        "slug": "sandbox-active-cpu",
        "usedDisplay": null,
        "limitDisplay": "5h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Provisioned Memory",
        "slug": "sandbox-provisioned-memory",
        "usedDisplay": null,
        "limitDisplay": "420 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Provisioned Memory",
        "slug": "vercel-functions-fluid-duration",
        "usedDisplay": null,
        "limitDisplay": "360 / 1,440 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Function Invocations",
        "slug": "vercel-functions-invocations",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      },
      {
        "label": "Edge Requests",
        "slug": "networking-edge-requests",
        "usedDisplay": null,
        "limitDisplay": "1M / 10M",
        "source": "dashboardOnly"
      },
      {
        "label": "Image Optimization - Transformations",
        "slug": "image-optimization-image-transformations",
        "usedDisplay": null,
        "limitDisplay": "5K / 10K",
        "source": "dashboardOnly"
      },
      {
        "label": "Fast Origin Transfer",
        "slug": "networking-fast-origin-transfer",
        "usedDisplay": null,
        "limitDisplay": "10 GB / 100 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "ISR Reads",
        "slug": "isr-reads",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      }
    ],
    "message": "خطة hobby لا تتيح Vercel Billing/Usage API لهذا النطاق."
  },
  "control": {
    "status": "ok",
    "capturedAt": "2026-09-18T12:05:47.764Z",
    "teamSlug": "01026546550",
    "ownerEmail": "tenderxcontractors@gmail.com",
    "planLabel": "hobby",
    "gitRepository": null,
    "billingPeriodStart": "2026-09-01T00:00:00.000Z",
    "billingPeriodEnd": "2026-09-18T12:05:47.764Z",
    "edgeRequestsLimit": 1000000,
    "fastDataTransferBytesLimit": 100000000000,
    "deploymentsPerDayLimit": 100,
    "buildsPerHourLimit": 100,
    "projectsLimit": 200,
    "runtimeLogsHoursLimit": 1,
    "functionDurationSecondsLimit": 300,
    "apiRateLimit": 400,
    "apiRateLimitRemaining": 399,
    "apiRateLimitReset": "2026-09-18T12:06:54.000Z",
    "billedCostUsd": null,
    "effectiveCostUsd": null,
    "billingLineCount": null,
    "topServices": [],
    "metrics": [
      {
        "label": "Snapshot Storage",
        "slug": "snapshot-storage",
        "usedDisplay": null,
        "limitDisplay": "15 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Active CPU",
        "slug": "vercel-functions-fluid-cpu-duration",
        "usedDisplay": null,
        "limitDisplay": "4h / 16h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Active CPU",
        "slug": "sandbox-active-cpu",
        "usedDisplay": null,
        "limitDisplay": "5h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Provisioned Memory",
        "slug": "sandbox-provisioned-memory",
        "usedDisplay": null,
        "limitDisplay": "420 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Provisioned Memory",
        "slug": "vercel-functions-fluid-duration",
        "usedDisplay": null,
        "limitDisplay": "360 / 1,440 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Function Invocations",
        "slug": "vercel-functions-invocations",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      },
      {
        "label": "Edge Requests",
        "slug": "networking-edge-requests",
        "usedDisplay": null,
        "limitDisplay": "1M / 10M",
        "source": "dashboardOnly"
      },
      {
        "label": "Image Optimization - Transformations",
        "slug": "image-optimization-image-transformations",
        "usedDisplay": null,
        "limitDisplay": "5K / 10K",
        "source": "dashboardOnly"
      },
      {
        "label": "Fast Origin Transfer",
        "slug": "networking-fast-origin-transfer",
        "usedDisplay": null,
        "limitDisplay": "10 GB / 100 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "ISR Reads",
        "slug": "isr-reads",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      }
    ],
    "message": "خطة hobby لا تتيح Vercel Billing/Usage API لهذا النطاق."
  },
  "submain": {
    "status": "ok",
    "capturedAt": "2026-09-18T12:05:47.764Z",
    "teamSlug": "283",
    "ownerEmail": "groupstenderximages@gmail.com",
    "planLabel": "hobby",
    "gitRepository": null,
    "billingPeriodStart": "2026-09-01T00:00:00.000Z",
    "billingPeriodEnd": "2026-09-18T12:05:47.764Z",
    "edgeRequestsLimit": 1000000,
    "fastDataTransferBytesLimit": 100000000000,
    "deploymentsPerDayLimit": 100,
    "buildsPerHourLimit": 100,
    "projectsLimit": 200,
    "runtimeLogsHoursLimit": 1,
    "functionDurationSecondsLimit": 300,
    "apiRateLimit": 400,
    "apiRateLimitRemaining": 399,
    "apiRateLimitReset": "2026-09-18T12:06:57.000Z",
    "billedCostUsd": null,
    "effectiveCostUsd": null,
    "billingLineCount": null,
    "topServices": [],
    "metrics": [
      {
        "label": "Snapshot Storage",
        "slug": "snapshot-storage",
        "usedDisplay": null,
        "limitDisplay": "15 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Active CPU",
        "slug": "vercel-functions-fluid-cpu-duration",
        "usedDisplay": null,
        "limitDisplay": "4h / 16h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Active CPU",
        "slug": "sandbox-active-cpu",
        "usedDisplay": null,
        "limitDisplay": "5h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Provisioned Memory",
        "slug": "sandbox-provisioned-memory",
        "usedDisplay": null,
        "limitDisplay": "420 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Provisioned Memory",
        "slug": "vercel-functions-fluid-duration",
        "usedDisplay": null,
        "limitDisplay": "360 / 1,440 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Function Invocations",
        "slug": "vercel-functions-invocations",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      },
      {
        "label": "Edge Requests",
        "slug": "networking-edge-requests",
        "usedDisplay": null,
        "limitDisplay": "1M / 10M",
        "source": "dashboardOnly"
      },
      {
        "label": "Image Optimization - Transformations",
        "slug": "image-optimization-image-transformations",
        "usedDisplay": null,
        "limitDisplay": "5K / 10K",
        "source": "dashboardOnly"
      },
      {
        "label": "Fast Origin Transfer",
        "slug": "networking-fast-origin-transfer",
        "usedDisplay": null,
        "limitDisplay": "10 GB / 100 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "ISR Reads",
        "slug": "isr-reads",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      }
    ],
    "message": "خطة hobby لا تتيح Vercel Billing/Usage API لهذا النطاق."
  },
  "sub2main": {
    "status": "ok",
    "capturedAt": "2026-09-18T12:05:47.764Z",
    "teamSlug": "773",
    "ownerEmail": "tenderx.engineer100@gmail.com",
    "planLabel": "hobby",
    "gitRepository": null,
    "billingPeriodStart": "2026-09-01T00:00:00.000Z",
    "billingPeriodEnd": "2026-09-18T12:05:47.764Z",
    "edgeRequestsLimit": 1000000,
    "fastDataTransferBytesLimit": 100000000000,
    "deploymentsPerDayLimit": 100,
    "buildsPerHourLimit": 100,
    "projectsLimit": 200,
    "runtimeLogsHoursLimit": 1,
    "functionDurationSecondsLimit": 300,
    "apiRateLimit": 400,
    "apiRateLimitRemaining": 399,
    "apiRateLimitReset": "2026-09-18T12:07:02.000Z",
    "billedCostUsd": null,
    "effectiveCostUsd": null,
    "billingLineCount": null,
    "topServices": [],
    "metrics": [
      {
        "label": "Snapshot Storage",
        "slug": "snapshot-storage",
        "usedDisplay": null,
        "limitDisplay": "15 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Active CPU",
        "slug": "vercel-functions-fluid-cpu-duration",
        "usedDisplay": null,
        "limitDisplay": "4h / 16h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Active CPU",
        "slug": "sandbox-active-cpu",
        "usedDisplay": null,
        "limitDisplay": "5h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Provisioned Memory",
        "slug": "sandbox-provisioned-memory",
        "usedDisplay": null,
        "limitDisplay": "420 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Provisioned Memory",
        "slug": "vercel-functions-fluid-duration",
        "usedDisplay": null,
        "limitDisplay": "360 / 1,440 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Function Invocations",
        "slug": "vercel-functions-invocations",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      },
      {
        "label": "Edge Requests",
        "slug": "networking-edge-requests",
        "usedDisplay": null,
        "limitDisplay": "1M / 10M",
        "source": "dashboardOnly"
      },
      {
        "label": "Image Optimization - Transformations",
        "slug": "image-optimization-image-transformations",
        "usedDisplay": null,
        "limitDisplay": "5K / 10K",
        "source": "dashboardOnly"
      },
      {
        "label": "Fast Origin Transfer",
        "slug": "networking-fast-origin-transfer",
        "usedDisplay": null,
        "limitDisplay": "10 GB / 100 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "ISR Reads",
        "slug": "isr-reads",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      }
    ],
    "message": "خطة hobby لا تتيح Vercel Billing/Usage API لهذا النطاق."
  },
  "notifications": {
    "status": "ok",
    "capturedAt": "2026-09-18T12:05:47.764Z",
    "teamSlug": "101-0902",
    "ownerEmail": "bs.bid.story@gmail.com",
    "planLabel": "hobby",
    "gitRepository": null,
    "billingPeriodStart": "2026-09-01T00:00:00.000Z",
    "billingPeriodEnd": "2026-09-18T12:05:47.764Z",
    "edgeRequestsLimit": 1000000,
    "fastDataTransferBytesLimit": 100000000000,
    "deploymentsPerDayLimit": 100,
    "buildsPerHourLimit": 100,
    "projectsLimit": 200,
    "runtimeLogsHoursLimit": 1,
    "functionDurationSecondsLimit": 300,
    "apiRateLimit": 400,
    "apiRateLimitRemaining": 399,
    "apiRateLimitReset": "2026-09-18T12:07:04.000Z",
    "billedCostUsd": null,
    "effectiveCostUsd": null,
    "billingLineCount": null,
    "topServices": [],
    "metrics": [
      {
        "label": "Snapshot Storage",
        "slug": "snapshot-storage",
        "usedDisplay": null,
        "limitDisplay": "15 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Active CPU",
        "slug": "vercel-functions-fluid-cpu-duration",
        "usedDisplay": null,
        "limitDisplay": "4h / 16h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Active CPU",
        "slug": "sandbox-active-cpu",
        "usedDisplay": null,
        "limitDisplay": "5h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Provisioned Memory",
        "slug": "sandbox-provisioned-memory",
        "usedDisplay": null,
        "limitDisplay": "420 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Provisioned Memory",
        "slug": "vercel-functions-fluid-duration",
        "usedDisplay": null,
        "limitDisplay": "360 / 1,440 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Function Invocations",
        "slug": "vercel-functions-invocations",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      },
      {
        "label": "Edge Requests",
        "slug": "networking-edge-requests",
        "usedDisplay": null,
        "limitDisplay": "1M / 10M",
        "source": "dashboardOnly"
      },
      {
        "label": "Image Optimization - Transformations",
        "slug": "image-optimization-image-transformations",
        "usedDisplay": null,
        "limitDisplay": "5K / 10K",
        "source": "dashboardOnly"
      },
      {
        "label": "Fast Origin Transfer",
        "slug": "networking-fast-origin-transfer",
        "usedDisplay": null,
        "limitDisplay": "10 GB / 100 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "ISR Reads",
        "slug": "isr-reads",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      }
    ],
    "message": "خطة hobby لا تتيح Vercel Billing/Usage API لهذا النطاق."
  },
  "products": {
    "status": "ok",
    "capturedAt": "2026-09-18T12:05:47.764Z",
    "teamSlug": "87-0bf2",
    "ownerEmail": "gnagnahesham@gmail.com",
    "planLabel": "hobby",
    "gitRepository": null,
    "billingPeriodStart": "2026-09-01T00:00:00.000Z",
    "billingPeriodEnd": "2026-09-18T12:05:47.764Z",
    "edgeRequestsLimit": 1000000,
    "fastDataTransferBytesLimit": 100000000000,
    "deploymentsPerDayLimit": 100,
    "buildsPerHourLimit": 100,
    "projectsLimit": 200,
    "runtimeLogsHoursLimit": 1,
    "functionDurationSecondsLimit": 300,
    "apiRateLimit": 400,
    "apiRateLimitRemaining": 399,
    "apiRateLimitReset": "2026-09-18T12:07:08.000Z",
    "billedCostUsd": null,
    "effectiveCostUsd": null,
    "billingLineCount": null,
    "topServices": [],
    "metrics": [
      {
        "label": "Snapshot Storage",
        "slug": "snapshot-storage",
        "usedDisplay": null,
        "limitDisplay": "15 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Active CPU",
        "slug": "vercel-functions-fluid-cpu-duration",
        "usedDisplay": null,
        "limitDisplay": "4h / 16h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Active CPU",
        "slug": "sandbox-active-cpu",
        "usedDisplay": null,
        "limitDisplay": "5h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Provisioned Memory",
        "slug": "sandbox-provisioned-memory",
        "usedDisplay": null,
        "limitDisplay": "420 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Provisioned Memory",
        "slug": "vercel-functions-fluid-duration",
        "usedDisplay": null,
        "limitDisplay": "360 / 1,440 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Function Invocations",
        "slug": "vercel-functions-invocations",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      },
      {
        "label": "Edge Requests",
        "slug": "networking-edge-requests",
        "usedDisplay": null,
        "limitDisplay": "1M / 10M",
        "source": "dashboardOnly"
      },
      {
        "label": "Image Optimization - Transformations",
        "slug": "image-optimization-image-transformations",
        "usedDisplay": null,
        "limitDisplay": "5K / 10K",
        "source": "dashboardOnly"
      },
      {
        "label": "Fast Origin Transfer",
        "slug": "networking-fast-origin-transfer",
        "usedDisplay": null,
        "limitDisplay": "10 GB / 100 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "ISR Reads",
        "slug": "isr-reads",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      }
    ],
    "message": "خطة hobby لا تتيح Vercel Billing/Usage API لهذا النطاق."
  },
  "orders": {
    "status": "ok",
    "capturedAt": "2026-09-18T12:05:47.764Z",
    "teamSlug": "434-49de",
    "ownerEmail": "tenderx10@gmail.com",
    "planLabel": "hobby",
    "gitRepository": null,
    "billingPeriodStart": "2026-09-01T00:00:00.000Z",
    "billingPeriodEnd": "2026-09-18T12:05:47.764Z",
    "edgeRequestsLimit": 1000000,
    "fastDataTransferBytesLimit": 100000000000,
    "deploymentsPerDayLimit": 100,
    "buildsPerHourLimit": 100,
    "projectsLimit": 200,
    "runtimeLogsHoursLimit": 1,
    "functionDurationSecondsLimit": 300,
    "apiRateLimit": 400,
    "apiRateLimitRemaining": 399,
    "apiRateLimitReset": "2026-09-18T12:07:11.000Z",
    "billedCostUsd": null,
    "effectiveCostUsd": null,
    "billingLineCount": null,
    "topServices": [],
    "metrics": [
      {
        "label": "Snapshot Storage",
        "slug": "snapshot-storage",
        "usedDisplay": null,
        "limitDisplay": "15 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Active CPU",
        "slug": "vercel-functions-fluid-cpu-duration",
        "usedDisplay": null,
        "limitDisplay": "4h / 16h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Active CPU",
        "slug": "sandbox-active-cpu",
        "usedDisplay": null,
        "limitDisplay": "5h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Provisioned Memory",
        "slug": "sandbox-provisioned-memory",
        "usedDisplay": null,
        "limitDisplay": "420 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Provisioned Memory",
        "slug": "vercel-functions-fluid-duration",
        "usedDisplay": null,
        "limitDisplay": "360 / 1,440 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Function Invocations",
        "slug": "vercel-functions-invocations",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      },
      {
        "label": "Edge Requests",
        "slug": "networking-edge-requests",
        "usedDisplay": null,
        "limitDisplay": "1M / 10M",
        "source": "dashboardOnly"
      },
      {
        "label": "Image Optimization - Transformations",
        "slug": "image-optimization-image-transformations",
        "usedDisplay": null,
        "limitDisplay": "5K / 10K",
        "source": "dashboardOnly"
      },
      {
        "label": "Fast Origin Transfer",
        "slug": "networking-fast-origin-transfer",
        "usedDisplay": null,
        "limitDisplay": "10 GB / 100 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "ISR Reads",
        "slug": "isr-reads",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      }
    ],
    "message": "خطة hobby لا تتيح Vercel Billing/Usage API لهذا النطاق."
  },
  "profiles": {
    "status": "ok",
    "capturedAt": "2026-09-18T12:05:47.764Z",
    "teamSlug": "656-1bdb",
    "ownerEmail": "hesham10125@gmail.com",
    "planLabel": "hobby",
    "gitRepository": null,
    "billingPeriodStart": "2026-09-01T00:00:00.000Z",
    "billingPeriodEnd": "2026-09-18T12:05:47.764Z",
    "edgeRequestsLimit": 1000000,
    "fastDataTransferBytesLimit": 100000000000,
    "deploymentsPerDayLimit": 100,
    "buildsPerHourLimit": 100,
    "projectsLimit": 200,
    "runtimeLogsHoursLimit": 1,
    "functionDurationSecondsLimit": 300,
    "apiRateLimit": 400,
    "apiRateLimitRemaining": 399,
    "apiRateLimitReset": "2026-09-18T12:07:14.000Z",
    "billedCostUsd": null,
    "effectiveCostUsd": null,
    "billingLineCount": null,
    "topServices": [],
    "metrics": [
      {
        "label": "Snapshot Storage",
        "slug": "snapshot-storage",
        "usedDisplay": null,
        "limitDisplay": "15 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Active CPU",
        "slug": "vercel-functions-fluid-cpu-duration",
        "usedDisplay": null,
        "limitDisplay": "4h / 16h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Active CPU",
        "slug": "sandbox-active-cpu",
        "usedDisplay": null,
        "limitDisplay": "5h",
        "source": "dashboardOnly"
      },
      {
        "label": "Sandbox Provisioned Memory",
        "slug": "sandbox-provisioned-memory",
        "usedDisplay": null,
        "limitDisplay": "420 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Fluid Provisioned Memory",
        "slug": "vercel-functions-fluid-duration",
        "usedDisplay": null,
        "limitDisplay": "360 / 1,440 GB-Hrs",
        "source": "dashboardOnly"
      },
      {
        "label": "Function Invocations",
        "slug": "vercel-functions-invocations",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      },
      {
        "label": "Edge Requests",
        "slug": "networking-edge-requests",
        "usedDisplay": null,
        "limitDisplay": "1M / 10M",
        "source": "dashboardOnly"
      },
      {
        "label": "Image Optimization - Transformations",
        "slug": "image-optimization-image-transformations",
        "usedDisplay": null,
        "limitDisplay": "5K / 10K",
        "source": "dashboardOnly"
      },
      {
        "label": "Fast Origin Transfer",
        "slug": "networking-fast-origin-transfer",
        "usedDisplay": null,
        "limitDisplay": "10 GB / 100 GB",
        "source": "dashboardOnly"
      },
      {
        "label": "ISR Reads",
        "slug": "isr-reads",
        "usedDisplay": null,
        "limitDisplay": "1M",
        "source": "dashboardOnly"
      }
    ],
    "message": "خطة hobby لا تتيح Vercel Billing/Usage API لهذا النطاق."
  }
} as const satisfies Record<string, CloudAccountsVercelUsageSnapshotRow>;
