/**
 * Safe Cloudflare R2 usage snapshot for `/dev/cloud-accounts`.
 *
 * Generated by `npm run cloud-accounts:r2-usage`. It contains numbers and
 * labels only: never API tokens, S3 access keys, or secret values.
 */

export type CloudAccountsR2UsageSnapshotStatus =
  | "ok"
  | "missingCredentials"
  | "apiError";

export type CloudAccountsR2UsageSnapshotRow = {
  readonly status: CloudAccountsR2UsageSnapshotStatus;
  readonly capturedAt: string | null;
  readonly periodStart: string | null;
  readonly periodEnd: string | null;
  readonly classAOperations: number | null;
  readonly classAOperationsLimit: number;
  readonly classBOperations: number | null;
  readonly classBOperationsLimit: number;
  readonly storageBytes: number | null;
  readonly storageBytesLimit: number;
  readonly objectCount: number | null;
  readonly uploadCount: number | null;
  readonly operationTypes: readonly string[];
  readonly message: string | null;
};

export const R2_USAGE_SNAPSHOT = {
  "general": {
    "status": "ok",
    "capturedAt": "2026-09-08T04:28:00.000Z",
    "periodStart": "2026-09-01T00:00:00.000Z",
    "periodEnd": "2026-09-08T04:28:00.000Z",
    "classAOperations": 276,
    "classAOperationsLimit": 1000000,
    "classBOperations": 56333,
    "classBOperationsLimit": 10000000,
    "storageBytes": 863652,
    "storageBytesLimit": 10000000000,
    "objectCount": 14,
    "uploadCount": 0,
    "operationTypes": [
      "ListObjects:54794",
      "HeadBucket:2",
      "HeadObject:807",
      "PutBucketCors:3",
      "GetBucketCors:38",
      "PutObject:273",
      "ListMultipartUploads:1",
      "GetObject:691"
    ],
    "message": "Captured through the connected Cloudflare account in Codex; local API token still lacks GraphQL Analytics access. Latest refresh: not authorized for that account. Latest refresh: not authorized for that account. Latest refresh: not authorized for that account. Latest refresh: not authorized for that account; browser fallback failed: fetch failed. Latest refresh: not authorized for that account; browser fallback failed: fetch failed. Latest refresh: not authorized for that account; browser fallback failed: fetch failed."
  },
  "products": {
    "status": "ok",
    "capturedAt": "2026-09-18T07:44:47.949Z",
    "periodStart": "2026-09-01T00:00:00.000Z",
    "periodEnd": "2026-09-18T07:44:47.949Z",
    "classAOperations": 120,
    "classAOperationsLimit": 1000000,
    "classBOperations": 272,
    "classBOperationsLimit": 10000000,
    "storageBytes": 79909,
    "storageBytesLimit": 10000000000,
    "objectCount": 3,
    "uploadCount": 0,
    "operationTypes": [
      "GetBucketNotificationConfiguration:1",
      "HeadBucket:6",
      "ListMultipartUploads:4",
      "ListObjects:111",
      "PutBucketCors:4",
      "GetObject:151",
      "GetBucketCors:105",
      "PutObject:1",
      "DeleteObject:1",
      "HeadObject:7",
      "GetBucketLifecycleConfiguration:1",
      "GetBucketSippyConfiguration:1"
    ],
    "message": null
  },
  "products-apparel-pets": {
    "status": "ok",
    "capturedAt": "2026-09-18T07:44:47.949Z",
    "periodStart": "2026-09-01T00:00:00.000Z",
    "periodEnd": "2026-09-18T07:44:47.949Z",
    "classAOperations": 110,
    "classAOperationsLimit": 1000000,
    "classBOperations": 77,
    "classBOperationsLimit": 10000000,
    "storageBytes": 0,
    "storageBytesLimit": 10000000000,
    "objectCount": 0,
    "uploadCount": 0,
    "operationTypes": [
      "HeadBucket:4",
      "PutBucketCors:2",
      "GetBucketCors:72",
      "ListObjects:105",
      "HeadObject:1",
      "ListMultipartUploads:3"
    ],
    "message": null
  },
  "ota": {
    "status": "ok",
    "capturedAt": "2026-09-18T07:44:47.949Z",
    "periodStart": "2026-09-01T00:00:00.000Z",
    "periodEnd": "2026-09-18T07:44:47.949Z",
    "classAOperations": 1403,
    "classAOperationsLimit": 1000000,
    "classBOperations": 73,
    "classBOperationsLimit": 10000000,
    "storageBytes": 75175504,
    "storageBytesLimit": 10000000000,
    "objectCount": 2029,
    "uploadCount": 0,
    "operationTypes": [
      "ListMultipartUploads:7",
      "HeadObject:14",
      "PutBucketCors:1",
      "ListObjects:25",
      "GetBucketCors:14",
      "HeadBucket:10",
      "DeleteObjects:1",
      "GetObject:35",
      "PutObject:1370"
    ],
    "message": null
  }
} as const satisfies Record<string, CloudAccountsR2UsageSnapshotRow>;
