/**
 * Safe Cloudflare R2 bucket contents snapshot for `/dev/cloud-accounts`.
 *
 * Generated by `npm run cloud-accounts:r2-contents`. It contains object
 * counts, byte totals, timestamps, and object keys only: never API tokens,
 * S3 access keys, or secret values.
 */

export type CloudAccountsR2ContentsSnapshotStatus =
  | "ok"
  | "missingCredentials"
  | "apiError";

export type CloudAccountsR2ContentsSnapshotRow = {
  readonly status: CloudAccountsR2ContentsSnapshotStatus;
  readonly capturedAt: string | null;
  readonly objectCount: number | null;
  readonly totalSizeBytes: number | null;
  readonly latestObjectKey: string | null;
  readonly latestObjectLastModified: string | null;
  readonly message: string | null;
};

export const R2_CONTENTS_SNAPSHOT = {
  "general": {
    "status": "ok",
    "capturedAt": "2026-09-18T07:44:51.818Z",
    "objectCount": 19,
    "totalSizeBytes": 1855082,
    "latestObjectKey": "gova-agent/public.json",
    "latestObjectLastModified": "2026-09-18T02:09:40.722Z",
    "message": null
  },
  "products": {
    "status": "ok",
    "capturedAt": "2026-09-18T07:44:51.818Z",
    "objectCount": 3,
    "totalSizeBytes": 79834,
    "latestObjectKey": "images/products/1/628e5bd9-8194-4268-885f-eb68fc916dc3.webp",
    "latestObjectLastModified": "2026-08-27T07:08:44.953Z",
    "message": null
  },
  "products-apparel-pets": {
    "status": "ok",
    "capturedAt": "2026-09-18T07:44:51.818Z",
    "objectCount": 0,
    "totalSizeBytes": 0,
    "latestObjectKey": null,
    "latestObjectLastModified": null,
    "message": null
  },
  "ota": {
    "status": "ok",
    "capturedAt": "2026-09-18T07:44:51.818Z",
    "objectCount": 2029,
    "totalSizeBytes": 75012204,
    "latestObjectKey": "app-updates/revocations.json",
    "latestObjectLastModified": "2026-09-17T05:13:11.115Z",
    "message": null
  }
} as const satisfies Record<string, CloudAccountsR2ContentsSnapshotRow>;
