import assert from "node:assert/strict"; import { createMemoryMarketplaceDb } from "../db/test-client"; import { MarketplaceOrderService } from "../services/marketplace-order-service"; import { validateImageAttachment } from "../validators";
async function main(){
  const db=createMemoryMarketplaceDb();
  const s=new MarketplaceOrderService(db),buyer={id:"buyer",role:"buyer" as const},seller={id:"seller",role:"seller" as const},seller2={id:"seller2",role:"seller" as const},admin={id:"admin",role:"admin" as const},carrier={id:"carrier",role:"carrier" as const};
  const order=await s.createMixedOrder({currency:"EGP",deliveryAddress:{city:"Cairo"}},buyer); const p1=await s.addOrderItem(order.id,{sellerId:seller.id,productId:"p1",productName:"Snapshot",quantity:2,unitPrice:1000,requiresSpecialVehicle:true,requiredVehicleType:"van"},buyer); const p2=await s.addOrderItem(order.id,{sellerId:seller2.id,productId:"p2",productName:"Other",quantity:1,unitPrice:500},buyer); const custom=await s.addCustomRequestItem(order.id,{sellerId:seller.id,title:"Pharmacy",buyerDescription:"Image list",requestType:"pharmacy",requiresRefrigeration:true},buyer);
  await s.addCustomRequestImage(custom.id,{storageProfileId:"spicialOrder",imageKey:"a.webp",mimeType:"image/webp",fileSize:123,imageUrl:"https://example.test/a.webp"},buyer); assert.throws(()=>validateImageAttachment({storageProfileId:"spicialOrder",imageKey:"bad.pdf",mimeType:"application/pdf",fileSize:1,imageUrl:"x"}),/images only/); await s.sellerAcceptItem(p1.id,seller); await s.sellerAcceptItem(p2.id,seller2); await s.sellerAcceptCustomRequest(custom.id,seller); await s.sellerSendPriceOfferForCustomRequest(custom.id,{unitPrice:800,quantity:1,expiresAt:new Date(Date.now()+60000).toISOString()},seller); await s.buyerAcceptCustomRequestPrice(custom.id,buyer);
  const shipment=await s.createShipment(order.id,{carrierId:carrier.id,shippingMethod:"road",pickupAddress:{},deliveryAddress:{}},admin); await s.assignOrderItemToShipment(shipment.id,p1.id,2,admin); await s.assignOrderItemToShipment(shipment.id,p2.id,1,admin); await s.assignCustomRequestItemToShipment(shipment.id,custom.id,1,admin); const refreshed=(await db.execute("SELECT * FROM shipments WHERE id=?",[shipment.id]))[0] as any; assert.equal(refreshed.contains_special_vehicle_items,1); assert.equal(refreshed.requires_refrigeration,1); await assert.rejects(()=>s.assignOrderItemToShipment(shipment.id,p1.id,1,admin)); await assert.rejects(()=>s.assignCustomRequestItemToShipment(shipment.id,custom.id,1,admin));
  const sis=await db.execute("SELECT id FROM shipment_items WHERE shipment_id=?",[shipment.id]); for(const x of sis)await s.carrierReceiveShipmentItem(String(x.id),carrier); await s.markShipmentInTransit(shipment.id,carrier); await s.markShipmentOutForDelivery(shipment.id,carrier); await s.markShipmentItemDelivered(String(sis[0].id),carrier); assert.equal(await s.recalculateShipmentStatus(shipment.id),"partially_delivered"); for(const x of sis.slice(1))await s.markShipmentItemDelivered(String(x.id),carrier); assert.equal(await s.recalculateShipmentStatus(shipment.id),"fully_delivered");
  await s.registerPayment(order.id,{buyerId:buyer.id,method:"wallet",amount:3300,currency:"EGP"},buyer); const refund=await s.createRefund(order.id,{amount:300,reason:"partial",orderItemId:p1.id},admin); await s.executeRefund(refund.id,admin); const ret=await s.createReturnRequest(order.id,{reason:"damaged",items:[{itemType:"order_item",orderItemId:p1.id,quantity:1}]},buyer); await s.approveReturnRequest(ret.id,seller); const dispute=await s.openDispute(order.id,{orderItemId:p1.id,reason:"condition"},buyer); await s.replyToDispute(dispute.id,"reviewed",seller); await s.adminResolveDispute(dispute.id,"partial refund",admin); const audits=await db.execute("SELECT * FROM audit_trail WHERE order_id=?",[order.id]); assert.ok(audits.length>=25); assert.equal((await db.execute("SELECT calculated_status FROM orders WHERE id=?",[order.id]))[0].calculated_status,"waiting_for_return"); console.log(`marketplace-orders: ${audits.length} audited actions passed`);
}
main().catch(error=>{console.error(error);process.exitCode=1});
